### ISSUE TITLE
Allow .editorconfig configuration files

### ISSUE THREAD

**Issue by colynb** [victorporof/Sublime-HTMLPrettify#105]
Most of my projects use the http://editorconfig.org/ standard. It would be nice if prettify loaded options from the .editorconfig - if exists - instead of .jsbeautifyrc.

**Comment by ZaLiTHkA** [comment]
I'd also love to see EditorConfig support for this.. Seems a bit redundant to set the same code formatting rules in both `.editorconfig` and `.jsbeautifyrc`.

**Comment by chrisyip** [comment]
+1.

For my team, we use EditorConfig as a style guide tool, it's fine with Atom, WebStorm, but not with Sublime Text + HTMLPrettify.

**Comment by srrvnn** [comment]
+1

**Comment by suicidepills** [comment]
+ 1

**Comment by victorporof** [comment]
It looks like this is getting a lot of demand. Is there anyone willing to contribute? (I could mentor)
If not, I'll see if I can find some time to write this.

**Comment by arthurcamara1** [comment]
:+1:

**Comment by trkailash** [comment]
Looks like this issue is still open. I will contribute but need mentoring. @victorporof

**Comment by toxsick** [comment]
+1

**Comment by erwingaitano** [comment]
+1, having to replicate .jsbeautifyrc settings with .editorconfig in every project is kind of annoying.

**Comment by xming13** [comment]
+1

**Comment by ZhongtianWang** [comment]
+1

**Comment by krystiangw** [comment]
:+1:

**Comment by smadapathi** [comment]
+1

**Comment by fimius23** [comment]
+1

**Comment by alimali** [comment]
+1

**Comment by ashwinurao** [comment]
+1

**Comment by bitwiseman** [comment]
@victorporof - this is enabled from the CLI in js-beautifier 1.6.4.  I'm not sure if that will help with this issue, but there it is.

**Comment by victorporof** [comment]
I'm surprised at the amount of demand for this. I'll work on this tomorrow (yay for vacation!).

Which editorconfig settings do you folks want to be supported? As far as I can tell only indentation size and indentation character are relevant.

**Comment by victorporof** [comment]
Initial support for editorconfig files is added in #374 and can be tested in the development branch, which should get merged into master as soon as testing is finished. Any help with testing would be appreciated
