### ISSUE TITLE
Detect the file type from the syntax highlighting option

### ISSUE THREAD

**Issue by taivu** [victorporof/Sublime-HTMLPrettify#111]
on a fresh install, went to prettify a minified CSS file. Every rule that has a hypen (ex: box-sizing), it adds space before and after the hyphen. So this set of rules:

<pre>box-sizing: border-box; box-shadow: 1px 1px 1px #fff; -webkit-appearance: none;</pre>

becomes:

<pre>
box - sizing: border - box;
box - shadow: 1px 1px 1px #fff;
- webkit - appearance: none;
</pre>

I'm on the latest ST3 (as of May 5th 2014).

everything else works fine: HTML, JS.

**Comment by disrupted** [comment]
> I'm guessing that ST3 tries to format the css as js, because it doesn't know what kind of file it is. Ideally we should try to fetch the file type from the syntax highlighting option as well.

@victorporof any news on this? for instance I'd like to disable Prettify for the UnityScript Syntax even though but the file has the standard **.js** extension.

**Comment by victorporof** [comment]
Fixed in #374
