### ISSUE TITLE
how can i make this prettify hbs extensions?

### ISSUE THREAD

**Issue by mgenev** [victorporof/Sublime-HTMLPrettify#115]
i write handlebars and auto-formatting is really pissing me off. any ideas? thanks!
edit: nvm found the answer by searching through closed issues

**Comment by wkerswell** [comment]
What was the fix?

**Comment by victorporof** [comment]
https://github.com/victorporof/Sublime-HTMLPrettify#specifying-your-own-file-extensions

**Comment by neilmonroe** [comment]
Note that there is a .jsbeautifyrc file in the plugin dir that is read first. You can change that file by going to the menu at:
Sublime Text > Preferences > Package Settings > HTML/CSS/JS Prettify > Set Prettify Preferences

By default (on OS X), this is in:
~/Library/Application Support/Sublime Text 3/Packages/HTML-CSS-JS Prettify/.jsbeautifyrc
