### ISSUE TITLE
Unnecessary spaces in PHP code

### ISSUE THREAD

**Issue by mrpavlikov** [victorporof/Sublime-HTMLPrettify#138]
I have some html file with php insertions:

``` html
<h1 class="content-page-header"><?=$view['name']; ?></h1>
```

After beautifying I use to have this:

``` html
<h1 class="content-page-header">
    <?=$view[ 'name']; ?>
</h1>
```

See that space right after `[`. 

Also code like this: 

``` html
<?= $view['content'][0]['descr']; ?>
```

becomes:

``` html
<?=$ view[ 'content'][0][ 'descr']; ?>
```

and ofc breaks syntax.

I seem to be unable to find the way to solve this. Is there any?

**Comment by finalight** [comment]
has this issue been solved yet? i also have the same problem and because of this i don't dare to reformat the codes with this plugin
