### ISSUE TITLE
Config files like .jsbeautifyrc reset to default when updating

### ISSUE THREAD

**Issue by mathiasr-infocorp** [victorporof/Sublime-HTMLPrettify#139]
Hi, I have been experiencing a rare issue along with a colleague. The `js.jslint_happy` on Preferences is resetted to `false` when we reboot both our PCs (separately). I don't know if it has to be with some issue with the `.jsbeautifyrc` file but it happens on my virtualized OSX 10.9.5 and his Windows 8.1 box.

Version: Sublime Text 3

Hope it helps.

**Comment by gabrielmaldi** [comment]
:+1:

**Comment by victorporof** [comment]
Update incoming

**Comment by MathiasLM** [comment]
This also happens when sublime or the computer crashes. I have had to write my settings at least 20 times by now.

**Comment by victorporof** [comment]
Again, I would suggest everyone keep .jsbeautifyrc settings in the project directory or home folder. Those files obviously won't be updated along with the plugin.

https://github.com/victorporof/Sublime-HTMLPrettify#using-your-own-jsbeautifyrc-options

**Comment by victorporof** [comment]
Fixed in #374
