### ISSUE TITLE
Ignore certain blocks of code

### ISSUE THREAD

**Issue by denniskoster** [victorporof/Sublime-HTMLPrettify#163]
Is it possible to leave certain blocks of codes from formatting? For instance, I have a compass mixin. The formatting process removes certain characters, therefore generating an error in my scss file.
For instance:
@if (sprite-position($sprites, $name) != sprite-position($sprites-retina, $name)) {
Becomes:
@if (sprite-position($sprites, $name) ! sprite-position($sprites-retina, $name)) {

Also, the plugin doesn't seem to understand php very well, rendering this:
<?= ML::label( 'member login')?>
Into:
<?=M L::label( 'member login')?>
Generating an error.

Thanks!

**Comment by askie** [comment]
+1

**Comment by PixelT** [comment]
+1

**Comment by CCSAweb** [comment]
+1

**Comment by Diex** [comment]
<?php ?> not work... :(

**Comment by gnicol-bzh** [comment]
Same kind of problem with scss var [interpolation](http://sass-lang.com/documentation/file.SASS_REFERENCE.html#interpolation_):
```css
@media #{$medium-up} { ... }
```
becomes
```css
@media # {
    $medium-up
}

{ 
...
}

**Comment by ldexterldesign** [comment]
+1

**Comment by finalight** [comment]
+1

**Comment by michaelprescott** [comment]
+1 for js-beautify's latest

/* beautify preserve:start */
...
/* beautify preserve:end */

**Comment by finalight** [comment]
so the above works/has been merged or just your suggestion?

**Comment by michaelprescott** [comment]
It is a suggestion.  Locally, I replaced Sublime-HTMLPrettify's js-beautify with the latest js-beautify and have that feature with no problems.

**Comment by victorporof** [comment]
Support for this was added in js-beautify: https://github.com/victorporof/Sublime-HTMLPrettify#ignoring-certain-blocks-of-code

It'd still be great if we could do it without the help of comments though.

**Comment by victorporof** [comment]
I suggest having a different issue for ignoring blocks of code via regexes (or some other method) in the plugin's settings.

**Comment by sodacrackers** [comment]
+1

**Comment by macandcheese** [comment]
Has the ability to ignore certain items been added? For instance, I want to ignore anything between "--- and ---" in an html file that contains config settings in that frontmatter.
