### ISSUE TITLE
Node.js was not found in the default path. Please specify the location.At mac os x 10.10.

### ISSUE THREAD

**Issue by ZacksTsang** [victorporof/Sublime-HTMLPrettify#166]
when i changed node_path to

```
"node_path":{
    "osx": "/usr/local/Cellar/node/0.10.32"
}
```

it did not work.

**Comment by LeonardoGentile** [comment]
This seems not to work again for me.
I've upgraded to Mac 10.11.6 and I'm using nvm.

My settings for the node path are:
```
 "node_path": {
    "windows": "C:/Program Files/nodejs/node.exe",
    "linux": "/usr/bin/nodejs",
    // nvm which current
    "osx": "/Users/foo/.nvm/versions/node/v6.3.1/bin/node"
  }
```

but anytime I hit the shortcuts for launching the command Sublime complains 
```
Node.js was not found in the default path. Please specify the location.
```

**Comment by gsivaprabu** [comment]
Had Error like below

![nodeerror](https://cloud.githubusercontent.com/assets/2444608/23691909/80088604-03f1-11e7-9ccb-914e43685f1b.jpg)

After click redirect to the settings page

![redirect](https://cloud.githubusercontent.com/assets/2444608/23691911/80214126-03f1-11e7-8c34-f8d75697747d.jpg)

Node installation path:-

![nodejsinstallationpath](https://cloud.githubusercontent.com/assets/2444608/23691950/b1cb73ea-03f1-11e7-9bca-1a4c160c846a.jpg)

**Comment by jiushiwoyuze** [comment]
@braankoo，it does work, great!

**Comment by saroepic** [comment]
@gsivaprabu  nice job. its working. thanks.
