### ISSUE TITLE
Support for Adding Spaces Between CSS Classes

### ISSUE THREAD

**Issue by mtpultz** [victorporof/Sublime-HTMLPrettify#189]
The CSS options seem to be fairly minimal for formatting would it be possible to expand these to allow for things like spacing between classes?

So instead of:

``` CSS
.myClass {
    ...
}
.myClass2 {
    ...
} 
```

it would look like:

``` CSS
.myClass {
    ...
}

.myClass2 {
    ...
} 
```

It makes the CSS easier to read, and with the prevalence of minification of CSS for production, developer readability is the only benefit to beautifying any HTML, CSS, or JS; and it seems like this plugin creates more of a non-expanded but not compressed version of the code in most cases outside of JS.

**Comment by ursulashan** [comment]
there is some wrong in less files .Such like if i wrote : 
div{
	margin-left: 10px;
} 
after the  formated the code would like this: 
div {
    margin - left: 10 px;
}
There was a useless spacing between each words and numbers.
