### ISSUE TITLE
Support Jekyll

### ISSUE THREAD

**Issue by ldexterldesign** [victorporof/Sublime-HTMLPrettify#192]
~ https://github.com/jekyll/jekyll/issues/3303

Apologies for crossposting :jack_o_lantern: 

Yours hopefully,

**Comment by ldexterldesign** [comment]
Hey,

Is it possible to add custom rules to the preferences file?

I'd like to the parser to add a new line every time the tool parses a double brace and percentage (i.e. {{% ) in a Jekyll/Liquid template

Yours hopefully,

**Comment by victorporof** [comment]
Can't add rules yet. Might be worth looking at https://github.com/victorporof/Sublime-HTMLPrettify/issues/163

**Comment by zellwk** [comment]
+1. 

I'm using Nunjucks and I'm encountering the same issues with {% %}

**Comment by victorporof** [comment]
Please file this bug at https://github.com/beautify-web/js-beautify
