### ISSUE TITLE
Plugin sometimes doesn't install on Sublime Text 3

### ISSUE THREAD

**Issue by curioussavage** [victorporof/Sublime-HTMLPrettify#193]
sublime text 3 package installs but does not show up in context menu, or in package settings

**Comment by victorporof** [comment]
Was this via the package manager? Git pull? Any other plugins installed? Any errors in sublime's console?

Please provide more details when filing a bug.

**Comment by curioussavage** [comment]
My mistake.

installed via package manager in sublime text 2 alongside other plugins, then sublime 3 was installed.
When 2 was uninstalled the package stopped working in version 3.

Did not look at the console.   I will see if I can recreate tomorrow if I can.

**Comment by victorporof** [comment]
Closing.
