### ISSUE TITLE
Jinja2 templates

### ISSUE THREAD

**Issue by hivre** [victorporof/Sublime-HTMLPrettify#195]
I'm writing a lot of jinja2 templates, which are almost like handlebars (`{{ var }}`, `{# comment #}`, `{% code %}`). 

Right now, on prettification, the plugin removes all newlines and indentation. 
This getting rather annoying, but I love the plugin and for css/html etc. it works great. 

Is there a way to let it ignore lines/code starting with curly braces (the current handlebars-setting has no effect), or make it indent jinja2 tags like normal html-tags?

**Comment by hivre** [comment]
might be a duplicate of #163

**Comment by victorporof** [comment]
Yeah, i think it's a dupe. https://github.com/victorporof/Sublime-HTMLPrettify/issues/163
