### ISSUE TITLE
Home folder on Windows 8

### ISSUE THREAD

**Issue by craiglondon** [victorporof/Sublime-HTMLPrettify#198]
What/where is the "Home" folder on Windows 8?

  // The plugin looks for a .jsbeautifyrc file in the same directory as the
  // source file you're prettifying (or any directory above if it doesn't exist,
  // or in your home folder if everything else fails) and uses those options
  // along the default ones.

**Comment by mtpultz** [comment]
Typically home on MAC defined by ~/ is equivalent to /c/users/username/

**Comment by craiglondon** [comment]
I put the file in my "C:\Users\Craig\" but I haven't been able to quite tell if that worked yet.

**Comment by victorporof** [comment]
http://en.wikipedia.org/wiki/Home_directory

C:\Users\Craig\ sounds about right

**Comment by craiglondon** [comment]
Can we reopen this issue?  Putting .jsbeautifyrc in my home folder "C:\Users\Craig" has no effect on the plugin.

If I edit "unformatted" in 
C:\Users\Craig\AppData\Roaming\Sublime Text 2\Packages\HTML-CSS-JS Prettify\.jsbeautifyrc
My change is respected.

Basically I just don't want LI's (list elements) to be formatted.

Below is my current .jsbeautifyrc in my home folder.
C:\Users\Craig\.jsbeautifyrc

{
  // The plugin looks for a .jsbeautifyrc file in the same directory as the
  // source file you're prettifying (or any directory above if it doesn't exist,
  // or in your home folder if everything else fails) and uses those options
  // along the default ones.

  // Details: https://github.com/victorporof/Sublime-HTMLPrettify#using-your-own-jsbeautifyrc-options
  // Documentation: https://github.com/einars/js-beautify/
  "html": {
    "allowed_file_extensions": ["ascx", "asp", "aspx", "htm", "html", "shtml", "php", "svg", "xhtml", "xml"],
    "indent_size": 2, // Indentation size
    "unformatted": ["a", "span", "li", "img", "code", "pre", "sub", "sup", "em", "strong", "b", "i", "u", "strike", "big", "small", "pre", "h1", "h2", "h3", "h4", "h5", "h6"], // List of tags that should not be reformatted
  },
  "css": {
    "indent_size": 2, // Indentation size
  },
  "js": {
    "indent_size": 2, // Indentation size
  }
}

**Comment by craiglondon** [comment]
I solved the issue, two things.
1) I should have removed the trailing commas from the last values in the "array".
2) The // comments were causing the JSON to not be valid.

I figured it out by running the command line
view.run_command("htmlprettify")

Then I saw this error
Could not parse JSON at: \Users\Craig\.jsbeautifyrc

Thanks for helping me use your wonderful plugin!

**Comment by victorporof** [comment]
Interesting, the comments should have been stripped away. Did you have comments in your .jsbeautifyrc?

**Comment by craiglondon** [comment]
My .jsbeautifyrc that had comments had some bad commas as well, once I corrected that.  It works fine! Thanks!
```
{
  "html": {
    "allowed_file_extensions": ["htm", "html", "php", "xhtml", "shtml", "xml", "svg"],
    "indent_size": 2, // Indentation size
    "unformatted": ["a", "span", "img", "li", "code", "pre", "sub", "sup", "em", "strong", "b", "i", "u", "strike", "big","small", "pre", "h1", "h2", "h3", "h4", "h5", "h6"] // List of tags that should not be reformatted
  },
  "css": {
    "indent_size": 2, // Indentation size
    "selector_separator_newline": true // Add a newline between multiple selectors
  },
  "js": {
    "allowed_file_extensions": ["js", "json", "jshintrc", "jsbeautifyrc"],
    "indent_size": 2 // Indentation size
  }
}
```
