### ISSUE TITLE
Update to js-beautify v1.5.5

### ISSUE THREAD

**Issue by gabrielmaldi** [victorporof/Sublime-HTMLPrettify#201]
Could `js-beautify` please be updated to [v1.5.5](https://github.com/beautify-web/js-beautify/blob/master/CHANGELOG.md#v155)? It now supports options for wrapping `HTML` attributes :smile: 

Thanks!

**Comment by xeroxoid** [comment]
+1

**Comment by joseluisq** [comment]
I agree. It's necessary update **js-beautify** to [v1.5.5](https://github.com/beautify-web/js-beautify/blob/master/CHANGELOG.md#v155) 
This version has many fixes and new options like: `newline_between_rules` for css.

**Comment by victorporof** [comment]
https://github.com/victorporof/Sublime-HTMLPrettify/commit/b5ef172d062b3fbefe31f475208e1b5525650807
