### ISSUE TITLE
Home folder on Windows

### ISSUE THREAD

**Issue by yanxyz** [victorporof/Sublime-HTMLPrettify#202]
When I put my `.jsbeautifyrc` in the home folder, it doesn't work. My OS is win8.1. Then I find out the problem. In the file `run.js`:

```js
function getUserHome() {
  return process.env.HOME || process.env.HOMEPATH || process.env.USERPROFILE;
}
```
However, the value of `process.env.HOMEPATH` doesn't have the driver, so the `.jsbeautifyrc` in the home folder won't be found. Fix it like this:

```js
function getUserHome() {
  return process.platform === 'win32' ? process.env.USERPROFILE : process.env.HOME;
}
```

**Comment by victorporof** [comment]
I don't understand what you mean by "the value of process.env.HOMEPATH doesn't have the driver"

**Comment by yanxyz** [comment]
In my pc the envionment variables is:

![image](https://cloud.githubusercontent.com/assets/737120/6701152/c0868de2-cd53-11e4-87ea-a94e2eb2f1e2.png)

so `process.env.HOMEPATH` return `\Users\yan`, not containing the drive. Then the plugin can't find the `.jsbeautifyrc` in the home folder when I'm under other drive.

**Comment by victorporof** [comment]
Oh, so instead of just "HOMEPATH", we should use HOMEDRIVE + HOMEPATH. I'll make this change.

**Comment by victorporof** [comment]
Please update to https://github.com/victorporof/Sublime-HTMLPrettify/commit/7822f962dffe569d69ff0feeda0e6aabed2ecb14 and let me know if it fixes things for you.

**Comment by yanxyz** [comment]
well, `process.env.USERPROFILE` maybe better, for in some windows `process.env.HOMEPATH` contains the drive. Refer to this discusstion:
http://stackoverflow.com/questions/9080085/node-js-find-home-directory-in-platform-agnostic-way
