### ISSUE TITLE
Where is the "home" folder if using Windows (for placement of .jsbeautifyrc)

### ISSUE THREAD

**Issue by sugardaddy** [victorporof/Sublime-HTMLPrettify#206]
the documentation says that the custom settings file (.jsbeautifyrc) can be placed in the user's "home folder" to make it apply to all files.  Where is that folder for a Windows user?

I've tried...
* `C:\ProgramFiles\SublimeText2` (the folder ST2 was installed in)
* `C:\Users\[username]\AppData\Roaming\Sublime Text 2` (the folder ST2 settings are stored in)
* `C:\Users\[username]\AppData\Roaming\Sublime Text 2\Packages`
* `C:\Users\[username]\AppData\Roaming\Sublime Text 2\Packages\User`

**Comment by victorporof** [comment]
https://en.wikipedia.org/wiki/Home_directory
