### ISSUE TITLE
Pseudo-classes formatted incorrectly and inconsistently with @page

### ISSUE THREAD

**Issue by dylanmensaert** [victorporof/Sublime-HTMLPrettify#207]
Pseudo-classes are being formatted incorrectly and inconsistently with @page:

<code>@page :first</code> -> <code>@page:first</code> -> <code>@page: first</code>

This is a problem since the last format is invalid css.
Is there a temporary fix where I can disable formatting of pseudo-classes?

**Comment by victorporof** [comment]
Please file this bug at https://github.com/beautify-web/js-beautify
