### ISSUE TITLE
Newline added when end_with_newline is false

### ISSUE THREAD

**Issue by mikerockett** [victorporof/Sublime-HTMLPrettify#210]
It seems that something isn't being fully honoured/respected here.

`end_with_newline` defaults to false, but a new line is added anyway. If I set this property to `true`, then *two* new lines are added.

The `ensure_newline_at_eof_on_save` is set to false in my Preferences.

Perhaps I'm missing another setting?

**Comment by junjs** [comment]
Same problem

**Comment by victorporof** [comment]
Does this still happen?

**Comment by mikerockett** [comment]
Indeed, it does.

**Comment by CaitlinWeb** [comment]
+1 Any plan to fix this?

Could be a bug with jsbeautify: https://github.com/beautify-web/js-beautify/issues/348

**Comment by denizdogan** [comment]
When I set it to true, it adds TWO newlines.
