### ISSUE TITLE
format problem with javascript

### ISSUE THREAD

**Issue by ChenWuLin** [victorporof/Sublime-HTMLPrettify#212]
my code:
    React.render( <CommentBox /> , document.getElementById('example'));

after format with shift+cmd+h:
   React.render( < CommentBox / > , document.getElementById('example'), < abc / > );

'< CommentBox / > ' isn't what I need.  how could I omit the ' ' after '/'?

**Comment by victorporof** [comment]
https://github.com/beautify-web/js-beautify is where you want to file this.
