### ISSUE TITLE
Read settings from .jsbeautifyrc placed in Sublime User folder

### ISSUE THREAD

**Issue by evenfrost** [victorporof/Sublime-HTMLPrettify#213]
Would be great if we could place `.jsbeautifyrc` file in Sublime User folder and use same config on different machines. My User folder is [synced](https://packagecontrol.io/docs/syncing) through Dropbox, and there are people who might find it handy as well.

**Comment by victorporof** [comment]
Good idea.

**Comment by lorenzogm** [comment]
Hello @victorporof , any news about this? It would be very useful to configure it somewhere inside "~/.config/sublime-text-3/Packages/User/"

Thanks!

**Comment by victorporof** [comment]
Not much time to work on this issue right now, but I'll gladly review pull requests. Otherwise I might get to this at some point in the future.

**Comment by LeonardoGentile** [comment]
I think this is solved by PR #296

**Comment by LeonardoGentile** [comment]
This is not working properly as it should.
Meaning, it will work after you place your .jsbeautifier file inside the User Folder.
As soon as sublime is quit and restarted then the default file will be read, not the custom one. If the plugin is removed and then re-installed then it will -restart working reading from the custom file. The if you quit Sublime and restart it will not work anymore.

**Comment by victorporof** [comment]
Fixed in #374
