### ISSUE TITLE
Adjacent and direct descendant selectors are not space separated

### ISSUE THREAD

**Issue by raduluchian** [victorporof/Sublime-HTMLPrettify#216]
Altought the CSS rule for "selector_separator" is set to " " (space character) this doesn't apply to rules that use direct descendant selectors or adjacent selectors. For example the following code...

    a+b {
        ...
    }

    a>b {
        ...
    }

... doesn't get formatted into this:

    a + b {
        ...
    }

    a > b {
        ...
    }

**Comment by victorporof** [comment]
Please file this bug at https://github.com/beautify-web/js-beautify
