### ISSUE TITLE
Error format scss @media queries

### ISSUE THREAD

**Issue by thanhrossi** [victorporof/Sublime-HTMLPrettify#217]
I used media queries in scss file
$phone: "only screen and (max-width : 767px)";
>h3{
    @media #{$phone} {
        font-size: 15px;
    }
}

But after press: Ctrl + Shift+ H 
>h3 {
   @media # {
            $phone
     }
     {
            font-size: 15px;
     }
}

Please help me fix this issue. HTMLPrettify very nice :)

**Comment by victorporof** [comment]
Please file this bug at https://github.com/beautify-web/js-beautify
