### ISSUE TITLE
Can't Nest Conditionals

### ISSUE THREAD

**Issue by loganknecht** [victorporof/Sublime-HTMLPrettify#219]
Hello!

I'm having an issue with my code where I want to nest conditional logic for better readability, however upon saving it causes the conditionals to be inlined together.

For example this is how I want the code to look

```javascript
if((!_.isNull(jqXHR.responseJSON) && !_.isUndefined(jqXHR.responseJSON)) 
   && (!_.isNull(jqXHR.responseJSON.errMessage) && !_.isUndefined(jqXHR.responseJSON.errMessage))) {
    signup_error_field.html(jqXHR.responseJSON.errMessage);
} else {
    signup_error_field.html('An Unexpected Error Occurred:\n' + error_thrown);
}
```

But, when I save it formats it to this

```javascript
if((!_.isNull(jqXHR.responseJSON) && !_.isUndefined(jqXHR.responseJSON)) && (!_.isNull(jqXHR.responseJSON.errMessage) && _.isUndefined(jqXHR.responseJSON.errMessage))) {
    signup_error_field.html(jqXHR.responseJSON.errMessage);
} else {
    signup_error_field.html('An Unexpected Error Occurred:\n' + error_thrown);
}

```

I tried changing multiple settings, however I wasn't able to really configure it such that it would match the desired style.

Is there a setting that would afford me this ability that I'm unaware of?

**Comment by victorporof** [comment]
Please file this bug at https://github.com/beautify-web/js-beautify
