### ISSUE TITLE
Sublime crash after formatting selection, then Enter/Return, then any other key

### ISSUE THREAD

**Issue by brandonjp** [victorporof/Sublime-HTMLPrettify#220]
I've been having a reliably reproduced error on my machine, just curious if anyone else can reproduce... 
- Select a block of code
- Use keyboard shortcut to format with HTMLPrettify
- After the format (code is no longer selected), hit the Enter or Return key 
- Then press any other key and Sublime crashes

(Note: ANY other keys can be pressed first, but if there has not been a mouse click then once Return has been pressed, any subsequent key will cause the crash)

I found myself accidentally/unintentionally causing it every now & then.  Not a huge problem for me now that I know what's causing it, but curious if others have the same issue

**Comment by victorporof** [comment]
This seems like a sublime issue. Please reopen if it's still annoying.
