### ISSUE TITLE
Beautify on save only selected types and/or extensions. 

### ISSUE THREAD

**Issue by maciekpaprocki** [victorporof/Sublime-HTMLPrettify#221]
It would be amazing if you could specify beautifying only selected extensions or types. Let's say I want to automatically beautify css files but html files should be beautified only on request.

It specially useful when you are  using custom html templating engine(where beautifying will probably destroy your formatting) but want to still use autobeautify on js and css.

**Comment by victorporof** [comment]
https://github.com/victorporof/Sublime-HTMLPrettify#specifying-your-own-file-extensions

**Comment by mattblang** [comment]
+1

**Comment by victorporof** [comment]
#374 adds a feature where certain files can be prevented from ever prettifying using a regex. Please reopen if this isn't sufficient for your needs
