### ISSUE TITLE
html format bug

### ISSUE THREAD

**Issue by zsytssk** [victorporof/Sublime-HTMLPrettify#226]
![qq 20150526104108](https://cloud.githubusercontent.com/assets/2304648/7806767/87abaf80-03b7-11e5-8100-662d37da6258.jpg)
to be
![qq 20150526104116](https://cloud.githubusercontent.com/assets/2304648/7806768/8a34c71e-03b7-11e5-8368-1d6be132ec42.jpg)

**Comment by victorporof** [comment]
Please file this bug at https://github.com/beautify-web/js-beautify
