### ISSUE TITLE
"indent_level" not working

### ISSUE THREAD

**Issue by Tain101** [victorporof/Sublime-HTMLPrettify#227]
Setting "indent_level" to any number doesn't change the indentation of script

    <script type="text/javascript">
    var x = 0;
    </script>

should change to 

    <script type="text/javascript">
        var x = 0;
    </script>

if "indent_level" = 1

Setting "indent_level" arbitrarily high (10+) still does not indent the script

**Comment by victorporof** [comment]
Please file this bug at https://github.com/beautify-web/js-beautify
