### ISSUE TITLE
Support for ES6 destructuring braces on single line

### ISSUE THREAD

**Issue by geirsagberg** [victorporof/Sublime-HTMLPrettify#231]
If I have an ES6 import declaration like this:
```import { assign } from 'lodash'```
HTMLPrettify will reformat this to:
```
import {
  assign
}
from 'lodash'
```
It would be nice to be able to specify that single-line braces should be kept on single line.

**Comment by thaiat** [comment]
also annotation are destructured
```js
@
Component({
        selector: 'my-app'
    })@ View({
        template: '<h1>Hello {{ name }}</h1>'
    })
    // Component controller
class MyAppComponent {
    name: string;

    constructor() {
        this.name = 'Alice';
    }
}
```

instead of 
```js
@Component({
  selector: 'my-app'
})
@View({
  template: '<h1>Hello {{ name }}</h1>'
})
// Component controller
class MyAppComponent {
  name: string;
  
  constructor() {
    this.name = 'Alice';
  }
}
```

**Comment by victorporof** [comment]
Please file this issue at https://github.com/beautify-web/js-beautify Would love to see support for this too.

**Comment by laggingreflex** [comment]
[A fix/hack has been proposed there](https://github.com/beautify-web/js-beautify/issues/668#issuecomment-119352753), in case anyone wants to try.

**Comment by harianus** [comment]
Looks like it is fixed in js-beautify (https://github.com/beautify-web/js-beautify/issues/668, https://github.com/beautify-web/js-beautify/issues/511, https://github.com/beautify-web/js-beautify/issues/382), does this mean it is also fixed in Sublime-HTMLPrettify?

**Comment by laggingreflex** [comment]
I've updated the node module directly, inside `Packages\HTML-CSS-JS Prettify\scripts` run `npm install js-beautify@latest`.

Also you have to use the new option `brace_style=collapse-preserve-inline` option for this.

**Comment by victorporof** [comment]
Updated to js-beautify 1.6.2
