### ISSUE TITLE
No option for newline in-between nested selectors in Sass

### ISSUE THREAD

**Issue by kmapoulter** [victorporof/Sublime-HTMLPrettify#232]
Currently when run in Sass, nested selectors look like this:
```
.class1 {
    text-color: black;
    .subClass1 {
        text-color: green;
        .anotherSubClass1 {
            text-color: blue;
        }
    }
    .subClass2 {
    	text-color: red;
    }
}
```

An option to add a newline in-between nested selectors in Sass that looks like the following would be wonderful!
```
.class1 {
    text-color: black;
    
    .subClass1 {
        text-color: green;
        
        .anotherSubClass1 {
            text-color: blue;
        }
    }
    
    .subClass2 {
    	text-color: red;
    }
}
```

Is there already an option that does this that I've missed, or is there a workaround?

**Comment by victorporof** [comment]
Please file this issue at https://github.com/beautify-web/js-beautify Not sure if a solution exists yet.

**Comment by mkstayalive** [comment]
Is there any option to preserve newlines for CSS, just like there is a config `"preserve_newlines"` for HTML / JS?
