### ISSUE TITLE
Blank line before and after CSS / JS comments

### ISSUE THREAD

**Issue by surjithctly** [victorporof/Sublime-HTMLPrettify#233]
It looks messy, when removing blank space before and after CSS / JS comments.

Instead of this.

    /* 
     * comment
     */ 
    /* another comment */
    body {
        ...
     }

I'd like to see this

    /* 
     * comment
     */
    
    /* another comment */
    
    body {
        ...
    }

**Comment by victorporof** [comment]
Please file this issue at https://github.com/beautify-web/js-beautify
