### ISSUE TITLE
Extract and format HTML withing a .php file

### ISSUE THREAD

**Issue by hartey11** [victorporof/Sublime-HTMLPrettify#235]
Hi,

started using HTML-CSS-JS Prettify in sublime text 2 and when I save a html file it formats on save. But when I save a php file nothing appears to happen, even if I include php as a filetype in my own .jsbeautifyrc file.

Could someone please let me know if its possible to format HTML within a php file and as a bonus format the php itself within the file?

Thanks in advance!

**Comment by victorporof** [comment]
This isn't supported yet. Would be great to extract the html and format it automatically.

**Comment by shaneparsons** [comment]
+1

**Comment by victorporof** [comment]
Please file this bug at https://github.com/beautify-web/js-beautify
