### ISSUE TITLE
formating scss :nth-child

### ISSUE THREAD

**Issue by Oeg87** [victorporof/Sublime-HTMLPrettify#237]
When I formatting my file SCSS by CMD + SHIFT + H, if inside I have a pseudo class  :nth-child(n), the formatting operation split the class (or tag) and the pseudoclass:

* I wrote: 
```css 
div:nth-child(3)
```
* Select the code I want format, CMD + SHIFT + H

* Result:
```css
div :nth-child(3)
```

When I run SASS, it give me, of course, an error for this.

In any case, very very useful, thank you for your job!

**Comment by victorporof** [comment]
Please file this issue at https://github.com/beautify-web/js-beautify
