### ISSUE TITLE
Unavailable on Package Control

### ISSUE THREAD

**Issue by aristidesfl** [victorporof/Sublime-HTMLPrettify#239]
Trying to install this plugin but it doesn't show up on the list of the `Package Control: Install Package` command.

It is available at https://packagecontrol.io/browse/authors/victorporof though.

Anyone can confirm?

**Comment by victorporof** [comment]
Shows up for me inside Sublime via Install Package.

**Comment by aristidesfl** [comment]
Ok, it was already installed, that's why it didn't show up. Thanks!
