### ISSUE TITLE
ES6 shorthand functions in object literals are not indented correctly

### ISSUE THREAD

**Issue by breakingco** [victorporof/Sublime-HTMLPrettify#244]
I can't show the formatting directly in here, but you can just cut and paste into Sublime to see what's going on.

this output is formatted correctly: 

  var es5obj = {
    foo: function() {
      return;
    },
    bar: function() {
      return;
    },
  };

But this is not. foo's closing bracket when written in es6 shorthand is indented an extra two spaces and subsequent functions line up with that bracket, triggering lint errors:

var es6obj = {
    foo() {
        return;
      },
      bar() {
        return;
      },
      bar() {
        return;
      },
  };

Thanks!

**Comment by victorporof** [comment]
Should file this at https://github.com/beautify-web/js-beautify
