### ISSUE TITLE
can we ignore certain lines of copy

### ISSUE THREAD

**Issue by alwayzambitious** [victorporof/Sublime-HTMLPrettify#248]
like tweenlite commands.... go to greensock.com, copy a command as  it's javascript...prettify it and you will see that it makes the command take up more than one lines because it assumes the tweenlite.to..... command is a function but it's not one.

**Comment by alwayzambitious** [comment]
Maybe lines that start with Tweenlite or TweenMax

**Comment by victorporof** [comment]
Don't think we should support this specifically.

**Comment by alwayzambitious** [comment]
What about generally, come on. Make it for any kind of text or lines of
code people choose, That sucks cause the code is not as readable.

**Comment by victorporof** [comment]
How would you implement such a thing? I'm not sure I fully understand what you're asking for.
