### ISSUE TITLE
Disable space between the right parenthesis ) and the left curly brace {

### ISSUE THREAD

**Issue by ReinoutvanKempen** [victorporof/Sublime-HTMLPrettify#249]
I'd like to disable the placing of a space char between the right parenthesis ) and the left curly brace { in my JavaScript functions. Is there a way I can configure the preferences or do something else to get the desired behavior?

function example(){

}

function(){

}

I now use 'replace with' to fix it after usage of Prettify but I'd like something automatic.

**Comment by victorporof** [comment]
Please file this bug at https://github.com/beautify-web/js-beautify
