### ISSUE TITLE
Breaks .dust templates tags. How to configure?

### ISSUE THREAD

**Issue by wzup** [victorporof/Sublime-HTMLPrettify#250]
I use Dust.js as a template engine. Among others Dust has these tags `{<_partial} ... {/_partial}`. I extended `"allowed_file_extensions"` option with `dust` file extension:
```
    "html": {
        "allowed_file_extensions": ["htm", "html", "xhtml", "shtml", "xml", "svg", "dust"],
```
But Sublime-HTMLPrettify breaks those tags. Instead of normal
```{<_main} ... {/_main} ```
it makes this:
```
{
<_main} ... {/_main}
```

How may say Sublime-HTMLPrettify not to break dust tags?

**Comment by victorporof** [comment]
Please file this bug at https://github.com/beautify-web/js-beautify
