### ISSUE TITLE
Review format selection

### ISSUE THREAD

**Issue by ldexterldesign** [victorporof/Sublime-HTMLPrettify#252]
Hey,

Haven't developed for a while, but today discovered you can apply formatting to selected text. I swear this never existed a year ago so thanks for the enhancement.

If I'm correct, and out of curiosity, when did this feature get released?

Especially useful now I'm working with http://handlebarsjs.com/

Thanks

**Comment by victorporof** [comment]
Probably this https://github.com/victorporof/Sublime-HTMLPrettify/commit/372c61c1a2cd927f183adbbb20f78a39e64a9dc5
