### ISSUE TITLE
Research HTML element formatting/wrapping - divs on new/individual line/s

### ISSUE THREAD

**Issue by ldexterldesign** [victorporof/Sublime-HTMLPrettify#253]
Hey,

Before:

<img width="536" alt="screen shot 2015-09-03 at 03 44 43" src="https://cloud.githubusercontent.com/assets/1715809/9648971/9da27e4c-51ee-11e5-9339-a4273b7d7102.png">

After (i.e. desired):

<img width="564" alt="screen shot 2015-09-03 at 03 44 57" src="https://cloud.githubusercontent.com/assets/1715809/9648974/a17385c0-51ee-11e5-9888-601584a8c08b.png">

I prefer the opening and closing tags to match position horizontally so I don't have to go looking for them

Help?

I would expect the following config option to relate but it doesn't :( :
```
"brace_style": "collapse", // [collapse|expand|end-expand|none] Put braces on the same line as control statements (default), or put braces on own line (Allman / ANSI style), or just put end braces on own line, or attempt to keep them where they are
```

Yours hopefully

**Comment by victorporof** [comment]
Please file this bug at https://github.com/beautify-web/js-beautify
