### ISSUE TITLE
/* beautify ignore */ does not work for HTML files

### ISSUE THREAD

**Issue by websirnik** [victorporof/Sublime-HTMLPrettify#260]
I have a not stable behaviour for `/* beautify ignore */ ` feature. When I create a new file, before specifying an extension, all works well. Beautify gets ignored if defined. The moment I save the file as `file.html` and the following code gets beautified despite the declaration to ignore beautify.
```html
/* beautify ignore:start */
<div><div>Test</div></div>
/* beautify ignore:end */
```
turns into
```html
/* beautify ignore:start */
<div>
    <div>Test</div>
</div>
/* beautify ignore:end */
```
I'm using standard config.

**Comment by glomotion** [comment]
I'm noticing the same problem with app engine objects inside a html file...

eg. 

'/* beautify ignore:start */

{% extends 'base.html' %}

{% block title %}Boilerplate index{% endblock %}

{% block container %}

<div>Hello, {{ name }}. This is an index page.</div>

{% endblock %}

/* beautify ignore:end */'

becomes:

'/* beautify ignore:start */ {% extends 'base.html' %} {% block title %}Boilerplate index{% endblock %} {% block container %}

<div>Hello, {{ name }}. This is an index page.</div>

{% endblock %} /* beautify ignore:end */'

**Comment by victorporof** [comment]
Please file this issue at https://github.com/beautify-web/js-beautify
