### ISSUE TITLE
Improper indentation {{else}} in combination with {{#unless}}

### ISSUE THREAD

**Issue by louwers** [victorporof/Sublime-HTMLPrettify#263]
Proper indentation with `{{#if ...}`:
![screen shot 2015-10-18 at 21 32 46](https://github-cloud.s3.amazonaws.com/assets/649392/10566184/fdccf7a6-75df-11e5-906c-7674946a9ed1.png)

Improper indentation with `{{#unless ...}}`:
![screen shot 2015-10-18 at 21 33 51](https://github-cloud.s3.amazonaws.com/assets/649392/10566182/f75f4b26-75df-11e5-96da-009a15fd4f75.png)

**Comment by victorporof** [comment]
Please file this bug at https://github.com/beautify-web/js-beautify
