### ISSUE TITLE
Grey and green highlighting after running

### ISSUE THREAD

**Issue by sbaldwin24** [victorporof/Sublime-HTMLPrettify#265]
![screen shot 2015-10-28 at 1 01 35 pm](https://cloud.githubusercontent.com/assets/5033746/10798141/1b489416-7d74-11e5-8058-08848504a184.png)
![screen shot 2015-10-28 at 1 00 35 pm](https://cloud.githubusercontent.com/assets/5033746/10798142/1b4b689e-7d74-11e5-9f8e-2c44b3fa82d8.png)

What or why are these grey and green highlights are running HTMLPrettify

**Comment by victorporof** [comment]
Not sure, I haven't seen them before...

**Comment by sbaldwin24** [comment]
Haven't had this issue in a while, appreciate the response!
