### ISSUE TITLE
Make Plugin Work in Paths that include UTF8 characters

### ISSUE THREAD

**Issue by bf** [victorporof/Sublime-HTMLPrettify#266]
According to a comment on issue #107 ( https://github.com/victorporof/Sublime-HTMLPrettify/issues/107#issuecomment-142729775 ), this plugin doesn't handle UTF8 characters in its path very well. Please fix this.

**Comment by bf** [comment]
Thanks to @scorpiohjx for raising this issue through his comment.

**Comment by bf** [comment]
Might be same as issue #126

**Comment by victorporof** [comment]
No, this project is not dead. It's an issue that is proving surprisingly difficult to fix in a cross platform all-locales all-charsets way. Feel free to contribute.

**Comment by victorporof** [comment]
Dupe of #126
