### ISSUE TITLE
I do not want to format script tag with src attribute

### ISSUE THREAD

**Issue by lscgzwd** [victorporof/Sublime-HTMLPrettify#269]
I do not want to format script tag with src attribute.

Like:
before format:
    &lt;script src="/static/AdminLTE/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.all.min.js">&lt;/script>

after:
    &lt;script src="/static/AdminLTE/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.all.min.js">

   &lt;/script&gt;

there are two empty line, i dot not want it , how can I set it .

**Comment by victorporof** [comment]
Please file this bug at https://github.com/beautify-web/js-beautify.
