### ISSUE TITLE
User settings lost on update?

### ISSUE THREAD

**Issue by laggingreflex** [victorporof/Sublime-HTMLPrettify#283]
I think a recent update made my user settings in `.jsbeautifyrc` lost and got overwritten with the defaults. Is this because `.jsbeautifyrc` is stored in the plugin itself, and not the the Packages\User space? If so it'd be nice to move those settings to user space

**Comment by eorroe** [comment]
Yes, was just about to post this, please fix this ASAP

**Comment by victorporof** [comment]
Indeed, this could be annoying. In the meantime, you should keep your own .jsbeautifyrc outside of the plugin's folder: https://github.com/victorporof/Sublime-HTMLPrettify#using-your-own-jsbeautifyrc-options

**Comment by andriisalamatin** [comment]
Yes, but you are checking plugin folder first and return as soon as your options found. Can you please check for user settings first?

> // Start with the current directory first, end with the user's home folder.
pathsToLook.reverse();
pathsToLook.push(getUserHome());
pathsToLook.some(function(pathToLook) {
  if (fs.existsSync(jsbeautifyrcPath = path.join(pathToLook, ".jsbeautifyrc"))) {
    setOptions(jsbeautifyrcPath, options);
    return true;
  }
});

**Comment by victorporof** [comment]
https://github.com/victorporof/Sublime-HTMLPrettify/issues/139
