### ISSUE TITLE
Closing 'body' tag isn't indented

### ISSUE THREAD

**Issue by jeremykohn** [victorporof/Sublime-HTMLPrettify#284]
Original text:

```
<!DOCTYPE html><html><head><meta charset="UTF-8"></head><body><h1>Hi!</h1></body></html>
```

After prettifying, all the text is indented properly -- except `</body>` after `</h1>`.

```
<!DOCTYPE html>
<html>

<head>
    <meta charset="UTF-8">
</head>

<body>
    <h1>Hi!</h1></body>

</html>
```

I'm using the latest version of Sublime Text 3 (Build 3103) on Mac OS X 10.10.5.

**Comment by victorporof** [comment]
Please file this bug at https://github.com/beautify-web/js-beautify

**Comment by jeremykohn** [comment]
Done.
