### ISSUE TITLE
Preserve attributes line break in HTML

### ISSUE THREAD

**Issue by rosco9awj** [victorporof/Sublime-HTMLPrettify#286]
Currently, running html prettify will concatenate a line a line of html code like this.
````html
<div id="anId" name="aName" class="aClass" onclick="alert('hello')">asdf</div>
<input type="text" name="aName" class="aClass" id="anId">
````
Could there be a wrap attributes option that will change the html as.
````html
<div id="anId"
       name="aName"
       class="aClass"
       onclick="alert('hello')">asdf</div>
<input type="text"
       name="aName"
       class="aClass"
       id="anId">
````
This is copied over from a closed js-beuttify issue, but I prefer using prettify and it is annoying not to have this feature.

**Comment by aske-cph** [comment]
:+1:

**Comment by aske-cph** [comment]
Mee too, makes the code a lot easier to read!

**Comment by victorporof** [comment]
Please file this bug at https://github.com/beautify-web/js-beautify
