### ISSUE TITLE
Last character is deleted when indenting

### ISSUE THREAD

**Issue by k-aymen** [victorporof/Sublime-HTMLPrettify#292]
The last character of the file is deleted when I use this package. Did anyone reported this before? 
I am using sublime 2 OSx

**Comment by kranthitech** [comment]
I am facing the same issue. Surprisingly, earlier it was working fine !

**Comment by coreystinson2** [comment]
+1

This is occurring for me in .css .scss .js and .html files. Last character of the file is being deleted when running the prettify command.
Reproduce by opening any new document, entering more than 1 character and running the command.

Plugin is practically unusable in this state.

Could it be related to this commit? https://github.com/victorporof/Sublime-HTMLPrettify/pull/261/commits/95813b22bef8ff1270b9c3c7f35f9bb10d044e0d

**Comment by Nineapsofttech** [comment]
coreystinson2 
I revert my machine [95813b2](https://github.com/victorporof/Sublime-HTMLPrettify/pull/261/commits/95813b22bef8ff1270b9c3c7f35f9bb10d044e0d) back to before merge code. every work again thanks

**Comment by coreystinson2** [comment]
Confirmed reverting https://github.com/victorporof/Sublime-HTMLPrettify/pull/261/commits/95813b22bef8ff1270b9c3c7f35f9bb10d044e0d manually has resolved this issue.

For OS X Locate the HTMLPrettify.py file under directory `/Users/{user}/Library/Application Support/Sublime Text 2/Packages` and revert the change made.

Confirmed issue is no longer occuring in .css .scss .js and .html files OS X

**Comment by yashvekaria** [comment]
Using ST2 on ubuntu 11.04, same issue occurs after the plugin was updated recently. Reverting to the previous commit solves it for me temporarily but i hope we have a permanent solution to this. Also it works fine for ST3 in a colleague's machine.

**Comment by simonkontschak** [comment]
+1

**Comment by JohannUlbrich** [comment]
Same here! +1

**Comment by victorporof** [comment]
Interesting. Ok, need to revert this changeset.

**Comment by victorporof** [comment]
Reverted! https://github.com/victorporof/Sublime-HTMLPrettify/commit/83b09227ae641de472c11e186846afdba18ac8b7
