### ISSUE TITLE
Is this still in Package Control?

### ISSUE THREAD

**Issue by bennlich** [victorporof/Sublime-HTMLPrettify#294]
I don't see it in sublime 2 package control :-/

**Comment by victorporof** [comment]
Should still be in. I didn't do anything specifically to remove it.

**Comment by bennlich** [comment]
Hrmn. Is anyone else unable to find it in package control? I'm entering "prettify". Package Control auto-updates it's list of packages, right? Can't figure out what I could be doing wrong...

**Comment by bennlich** [comment]
Oh, rofl. It's already installed...
