### ISSUE TITLE
Messing up jsx formatting

### ISSUE THREAD

**Issue by buinauskasevaldas** [victorporof/Sublime-HTMLPrettify#297]
I've got latest version installed. My files are opened as Babel JS files and I have e4x set to true in my configuration file. This is what I have currently:

```
return (
  <a href="#"
    onClick={e => {
      e.preventDefault()
      onClick()
    }}>
    {children}
  </a>
);
```

However, after formatting it becomes this:

```
return ( < a href = "#"
  onClick = {
    e => {
      e.preventDefault()
      onClick()
    }
  } > { children } < /a>
);
```

What do I need to change to have my files formatted properly or at least not messed up?

**Comment by victorporof** [comment]
Please file this bug at https://github.com/beautify-web/js-beautify
Would really really love to get jsx formatting too.

**Comment by iiitmahesh** [comment]
@victorporof how to use this in sublime editor
