### ISSUE TITLE
preserve_newlines don't work for js in html

### ISSUE THREAD

**Issue by s-trooper** [victorporof/Sublime-HTMLPrettify#298]
Hi, i have ``` "max_preserve_newlines": 1, "preserve_newlines": true``` for both JS and HTML config but the new lines are not preserved for JS in html like this:
```html
<body unresolved>
  <file-tracking></file-tracking>
  <script>
  var x = "1";
 
  var y = "2";
  </script>
</body>

```

**Comment by victorporof** [comment]
Please file this bug at https://github.com/beautify-web/js-beautify
