### ISSUE TITLE
Ignore blade laravel syntax

### ISSUE THREAD

**Issue by funnyfrontend** [victorporof/Sublime-HTMLPrettify#299]
I add php to Prettify .jsbeautifyrc file:
`"html": {
        "allowed_file_extensions": ["htm", "html", "xhtml", "shtml", "xml", "svg", "php"],`

But, when I use a index.blade.php Laravel syntax for example, the code drive crazy.

input:
```
@extends('layout.master_page')

@section('metas')
@parent
<meta name="alexaVerifyID" content="asdfasdfasdf" />
@stop
```

output:
`@extends('layout.master_page') @section('metas') @parent
<meta name="alexaVerifyID" content="asdfasdfasdf" /> @stop
`

I try add some laravel syntax to "unformatted" property, but this not works:
`"unformatted": ["@extends","@section","@stop","a", "span",`

**Comment by victorporof** [comment]
Please file this at https://github.com/beautify-web/js-beautify
