### ISSUE TITLE
Suggestion: add newline for selected attibutes such as 'xmlns' options in configuration file

### ISSUE THREAD

**Issue by jjff** [victorporof/Sublime-HTMLPrettify#303]
I'm newbie, in github as well as sublime text.

xmlns are normally quite long strings that you normally want to be easily readable as reference in an xhtml file. But perhaps this is more xml than modern html5...

**Comment by victorporof** [comment]
Doesn't seem like a bad idea.

**Comment by victorporof** [comment]
Please file this bug at https://github.com/beautify-web/js-beautify
