### ISSUE TITLE
Add feature to convert double quote into single quote?

### ISSUE THREAD

**Issue by ibbatta** [victorporof/Sublime-HTMLPrettify#304]
Could you implement a feature to convert double quotes `"` into single quotes `'` for javascript?

**Comment by victorporof** [comment]
What's wrong with find and replace?

**Comment by ibbatta** [comment]
Well, to adopt a common codestyle, devs in our office could "replace double quotes" simply on save.
This save time and errors chance.

**Comment by trevorgreenleaf** [comment]
+1
