### ISSUE TITLE
CSS prettifying Error with styling placeholder

### ISSUE THREAD

**Issue by vajahath** [victorporof/Sublime-HTMLPrettify#307]
Prettifying css removes a space from the code.
The code below is used to style placeholders.

**working code**
```
.card-blue ::-webkit-input-placeholder {
	color: #87D1FF;
}
``` 
**incorrect code after prettification** (Notice the space)
```
.card-blue::-webkit-input-placeholder {
	color: #87D1FF;
}
```
I tested it in google chrome. I recommend you to test this in all other browsers.

**Comment by victorporof** [comment]
Please file this at https://github.com/einars/js-beautify
