### ISSUE TITLE
ignore script sections with a non-standard type attribute

### ISSUE THREAD

**Issue by iambrosie** [victorporof/Sublime-HTMLPrettify#309]
Hi,

I've noticed that if I use a _script_ tag with the type attribute set to "javascript/worker" (i.e. not a JavaScript MIME type) - see [here ](https://jsfiddle.net/2ppc01cq/) for an example , then the _script_'s innerHTML will all be treated as one long comment.
I believe the plugin should not try to format script tags with non-JavaScript MIME types.

P. S. This is annoying only when i use the plugin with the format on save option activated. 

Regards!

**Comment by victorporof** [comment]
Please file this bug at https://github.com/beautify-web/js-beautify
