### ISSUE TITLE
&:first-of-type:not(:last-child) when prettified insert erroneous white character

### ISSUE THREAD

**Issue by gvocale** [victorporof/Sublime-HTMLPrettify#310]
When I prettify the following code:

`.div {
    &:first-of-type:not(:last-child) {}
}
`

the result is:

`.div {
    &:first-of-type:not(: last-child) {}
}
`

Which throws an error in sass, because there is a spacing before "last-child".

**Comment by mayaa6** [comment]
I encountered the same problem. Is there anyone do sth solve it?

**Comment by victorporof** [comment]
Please file this bug at https://github.com/beautify-web/js-beautify

**Comment by gvocale** [comment]
I'll do.

How come do I file it with JS beautify? Isn't it related to how the CSS is beautified?

**Comment by victorporof** [comment]
That library is also used for css beautification.
