### ISSUE TITLE
Using the plugin with rails tags

### ISSUE THREAD

**Issue by dkey94** [victorporof/Sublime-HTMLPrettify#312]
Hi!
I'd like to know how can I use Sublime-HTMLPretiffy plugin with rails tags. I have file called "index.html.erb" which contains HTML code + rails tags. Ex:
```
<p><%= notice %></p>
Or
<p>
<% if notice.present? %>
Some notice :)
<% end %>
</p>
```
Here are my settings: 

>   "html": {
>     "allowed_file_extensions": ["htm", "html", "xhtml", "shtml", "xml", "svg", "html.erb"],
>     "brace_style": "collapse", // [collapse|expand|end-expand|none] Put braces on the same line as control statements (default), or put braces on own line (Allman / ANSI style), or just put end braces on own line, or attempt to keep them where they are
>     "end_with_newline": false, // End output with newline
>     "indent_char": " ", // Indentation character
>     "indent_handlebars": true, // e.g. {{#foo}}, {{/foo}}
>     "indent_inner_html": false, // Indent <head> and <body> sections
>     "indent_scripts": "keep", // [keep|separate|normal]
>     "indent_size": 4, // Indentation size
>     "max_preserve_newlines": 0, // Maximum number of line breaks to be preserved in one chunk (0 disables)
>     "preserve_newlines": true, // Whether existing line breaks before elements should be preserved (only works before elements, not inside tags or for text)
>     "unformatted": ["%", "%=", "a", "span", "img", "code", "pre", "sub", "sup", "em", "strong", "b", "i", "u", "strike", "big", "small", "pre", "h1", "h2", "h3", "h4", "h5", "h6"], // List of tags that should not be reformatted
>     "wrap_line_length": 0 // Lines should wrap at next opportunity after this number of characters (0 disables)
>   },

Thanks!

**Comment by victorporof** [comment]
Please file this bug at https://github.com/beautify-web/js-beautify
