### ISSUE TITLE
CSS Formatting puts spaces around dash (ST3)

### ISSUE THREAD

**Issue by codeThaGlobe** [victorporof/Sublime-HTMLPrettify#316]
Before
`.impact-icon{ margin-right: 4px; display: inline-block}`

After
```
.impact - icon { margin - right: 4 px;
         display: inline - block }
```

Anyone else having this issue?
Any fix?

**Comment by lifetin** [comment]
I like the effect of a single line, I would like to ask how to set up?
.impact-icon{ margin-right: 4px; display: inline-block}

**Comment by victorporof** [comment]
Please file this bug at https://github.com/beautify-web/js-beautify

**Comment by stantyan** [comment]
Was this bug been solved? I'm using ST3 and latest version of Sublime-HTMLPrettify. Here is what I get:

Before:
`.class-sample .va-picker .va-text {
min-width: 50px !important;
min-height: 0px !important;
font-size: 18px !important;
height: 50px !important;
line-height: 2.0 !important;
-webkit-border-radius: 200px !important;
-moz-border-radius: 200px !important;
border-radius: 200px !important;
}`

After:
`.class - sample.va - picker.va - text {
    min - width: 50 px!important;
    min - height: 0 px!important;
    font - size: 18 px!important;
    height: 50 px!important;
    line - height: 2.0!important; - webkit - border - radius: 200 px!important; - moz - border - radius: 200 px!important;
    border - radius: 200 px!important;
}`

How to solve this problem?
