### ISSUE TITLE
Error: Insertion of a whitespace character while formatting

### ISSUE THREAD

**Issue by francjohny** [victorporof/Sublime-HTMLPrettify#320]
Adds a whitespace after ':' when using :last-child Selector

_Current version of Sublime Text - Build 3114_
![screen shot 2016-06-21 at 4 33 36 pm](https://cloud.githubusercontent.com/assets/10945677/16227498/85824736-37ce-11e6-89bf-ecb93323b8cd.png)

**Comment by victorporof** [comment]
Please file this bug here https://github.com/einars/js-beautify
