### ISSUE TITLE
<dfn> tag

### ISSUE THREAD

**Issue by Kristinita** [victorporof/Sublime-HTMLPrettify#324]
My text formatted your plugin:

```
В силу причин
<dfn>а</dfn> и
<dfn>в</dfn> я вообще стараюсь не использовать программы, сохраняющие какие-либо пользовательские данные на системном диске.
```

I believe that [<dfn> tag should not be moved](http://www.w3schools.com/tags/tag_dfn.asp) to a new line, I think it should be so:

```В силу причин <dfn>а</dfn> и <dfn>в</dfn> я вообще стараюсь не использовать программы, сохраняющие какие-либо пользовательские данные на системном диске.```

Thanks.

**Comment by victorporof** [comment]
Please file this bug at https://github.com/einars/js-beautify

**Comment by Kristinita** [comment]
@victorporof , is not js-beautify problem, see [answer](https://github.com/beautify-web/js-beautify/issues/966#issuecomment-243330026). With `<kbd>` tag I have the same problem. Thanks.
