### ISSUE TITLE
stop HTML comments bouncing to new line on prettify

### ISSUE THREAD

**Issue by Tommy-B-Git** [victorporof/Sublime-HTMLPrettify#325]
Hi. Can anyone help me with this? Had a play around with some of the settings in the Preferences to no avail.

**Comment by victorporof** [comment]
Please file this bug at https://github.com/beautify-web/js-beautify

**Comment by mazadah** [comment]
Was this resolved yet? I want the code to stay like this:
`<div id="wrapper">
	<div class="container">

	</div>
</div>
`
