### ISSUE TITLE
Redundant newline when "end_with_newline" is true

### ISSUE THREAD

**Issue by seoker** [victorporof/Sublime-HTMLPrettify#326]
I was formatting a JS file using HTMLPrettify with `end_with_newline` set to `true` in my `.jsbeautifyrc` file and it turns out two newline at the end of file rather than one. If I set to `false`, no newline will be appended. Hence I think the result is caused by _HTMLPrettify_ alone, not by multiple plugins with more than two produce newlines.

Any one could help, please? Thanks.

**Comment by andrewadare** [comment]
I also am seeing this redundant newline problem.

**Comment by amtrack** [comment]
me too

**Comment by willyb321** [comment]
Me three.

**Comment by amit1911** [comment]
+1

**Comment by victorporof** [comment]
Fixed in #374
