### ISSUE TITLE
add *.vue support?

### ISSUE THREAD

**Issue by leafiy** [victorporof/Sublime-HTMLPrettify#327]
add *.vue support?

**Comment by aristidesfl** [comment]
+1

**Comment by webbur** [comment]
+1

**Comment by adammacias** [comment]
+1

**Comment by Cedric-song** [comment]
mark

**Comment by anyclub** [comment]
+1s?

**Comment by benjaminpwarren** [comment]
+700

**Comment by victorporof** [comment]
Please file this bug at https://github.com/beautify-web/js-beautify

**Comment by aristidesfl** [comment]
@victorporof but `*.vue` files usually contain html and css, not only JS

**Comment by victorporof** [comment]
`js-beautify` already supports prettifying js inside html as far as I know, and I'm not sure if the scope of this plugin is to support parsing file contents (which already happens inside the prettifier). In the interest of separating concerns, I'm delegating this to `js-beautify`. If there's a clear expectancy to have this kind of parsing outside of the prettifier, then I agree it should happen in this plugin instead.

**Comment by kospol** [comment]
+1

**Comment by phaibin** [comment]
Just add "vue" for support html extensions in "global_file_rules".

**Comment by mesqueeb** [comment]
I tried to add "vue" in the "global_file_rules".
I want it to clean up my HTML, JS and CSS in the vuefile, so I add it at each of the "allowed_file_extensions" of "html", "css" and "js" respectively:

```
{
    // Settings determining which files are allowed to be prettified.
    // All the keys below need to be included in your user settings for them to work.
    "global_file_rules":
    {
        // Be sure to include the `html` key in your user settings to be able
        // to prettify html files.
        "html":
        {
            "allowed_file_extensions": ["htm", "html", "xhtml", "shtml", "xml", "svg", "vue"],
            "allowed_file_syntaxes": ["html", "xml"],
            "disallowed_file_patterns": []
        },
        // Be sure to include the `css` key in your user settings to be able
        // to prettify css files.
        "css":
        {
            "allowed_file_extensions": ["css", "scss", "sass", "less", "vue"],
            "allowed_file_syntaxes": ["css", "sass", "less"],
            "disallowed_file_patterns": []
        },
        // Be sure to include the `js` key in your user settings to be able
        // to prettify js files.
        "js":
        {
            "allowed_file_extensions": ["js", "vue"],
            "allowed_file_syntaxes": ["javascript", "ecma"],
            "disallowed_file_patterns": []
        },
    },
}
```

**problem**
However, in my HTML, where I have the vue brackets: {{}} it starts putting each bracket on a new line because of my allman settings...

Any ideas how to stop this?
