### ISSUE TITLE
exception msg may misslead users

### ISSUE THREAD

**Issue by lqniu** [victorporof/Sublime-HTMLPrettify#328]
In file HTMLPrettify.py Line 103 and 104, you catch the exception and write "# Usually, it's just node.js not being found. Try to alleviate the issue." 
In my case, I opened an file in path with Chinese characters, and I got the err msg "Node.js was not found in the default path. Please specify the location." , which misslead me , i have check my nodejs config and reinstall it , but it doesn't work, finally i print the cmd and find the real caution.
I suggest you to give the Explicit err msg.

**Comment by victorporof** [comment]
Handling this much better in #374
