### ISSUE TITLE
Use current indent settings instead of hardcoded in command

### ISSUE THREAD

**Issue by henrahmagix** [victorporof/Sublime-HTMLPrettify#33]
The following is hardcoded in HTMLPrettify.py, but should be retrieved from the current window settings:

``` javascript
{
    "indent_size": 2,
    "indent_char": " "
}
```

**Comment by erquhart** [comment]
3 year old issue - is this happening? Need a PR?

**Comment by victorporof** [comment]
Would love a PR :1

**Comment by victorporof** [comment]
Fixed in #374

**Comment by henrahmagix** [comment]
@victorproof Thanks for working on this! Very much appreciated. But shouldn't this issue only be closed when the PR is merged and released?

**Comment by victorporof** [comment]
@henrahmagix It's fixed on the development branch, which anyone can try out. I plan on merging it to master as soon as I test everything on Sublime 2 and 3 on other operating systems than mine (tomorrow). Any help appreciated!
