### ISSUE TITLE
Does not work on Linux

### ISSUE THREAD

**Issue by rafaelvectar** [victorporof/Sublime-HTMLPrettify#330]
When I run "Prettify Code" it gives me this error at console:

Using node.js path on 'linux': /usr/bin/nodejs
Could not parse JSON at: /home/rafael/.config/sublime-text-3/Packages/HTML-CSS-JS Prettify/.jsbeautifyrc
Using prettify options: {
  "html": {},
  "css": {},
  "js": {}
}

The file .jsbeautifyrc exists and probably the error is tha node.js need to be called with the path inside quotation marks, like this:

nodejs "/home/rafael/.config/sublime-text-3/Packages/HTML-CSS-JS Prettify/.jsbeautifyrc"

Or using a \ as an escape char, like this:

nodejs /home/rafael/.config/sublime-text-3/Packages/HTML-CSS-JS\ Prettify/.jsbeautifyrc

Can you help me?

**Comment by victorporof** [comment]
#374 might be fixing this, I couldn't reproduce the issue myself. Please reopen if not.
