### ISSUE TITLE
Unnecessary indent found

### ISSUE THREAD

**Issue by leafiy** [victorporof/Sublime-HTMLPrettify#331]
``` javascript
export default {
    data() {
```

my configuration is 2 spaces, so it should be

``` javascript
export default {
  data() {
```

**Comment by bitwiseman** [comment]
This may be fixed in the latest js-beautifier 1.6.4.  Please update and try it out.

**Comment by victorporof** [comment]
Please file this bug at https://github.com/beautify-web/js-beautify
