### ISSUE TITLE
How to disable "disable-preserve-newlines" for css

### ISSUE THREAD

**Issue by jasjuang** [victorporof/Sublime-HTMLPrettify#339]
Lets say I have code

``````
// Variables

// Gray and Brand Colors for use across theme

@theme - primary: # F05F40;
``````

No matter what I set for the arguments "allowed_file_extensions", "end_with_newline", "indent_char", "indent_size", "newline_between_rules", "selector_separator", "selector_separator_newline" it always gets format to

``````
// Variables
// Gray and Brand Colors for use across theme
@theme - primary: # F05F40;
``````

However, if I run it on the command line (I am on Ubuntu 14.04),  

``````
js-beautify test.css
``````

it returns 

``````
// Variables

// Gray and Brand Colors for use across theme

@theme - primary: # F05F40;
``````

only if I run 

``````
js-beautify --disable-preserve-newlines test.css
``````

it will return 

``````
// Variables
// Gray and Brand Colors for use across theme
@theme - primary: # F05F40;
``````

How can I disable "--disable-preserve-newlines" in sublime?

**Comment by laggingreflex** [comment]
Config is stored in a file called `.jsbeautifyrc` and by default the sublime package comes with its own version of it. But you can easily override it by having it in your homedir or even your project dir.

**Comment by jasjuang** [comment]
I created a new .jsbeautifyrc in my project dir, but what should I put in it?

I tried

``````
"css": {
    "disable_preserve_newlines": false
  },
``````

The result is still the same. Were you able to successfully disable "--disable-preserve-newlines"?

**Comment by laggingreflex** [comment]
Try `"preserve_newlines": true`

**Comment by jasjuang** [comment]
doesn't work for me, ctrl+shift+h still kills the newline, but running on command line with 

``````
js-beautify test.css
``````

preserves the newline

Did it work for you?

**Comment by laggingreflex** [comment]
I hadn't tried it until now. You're right, it doesn't work. It seems there isn't actually an option [for CSS][1] to preserve newlines. The correct CLI syntax for CSS is `js-beautify --css test.css` otherwise it was probably just treating it as JS which does has that option (or it could be returning it unchanged)

[1]: https://github.com/beautify-web/js-beautify#css--html

**Comment by jasjuang** [comment]
You are right, it's being treated as a js file. If I add the --css flag the newline is gone. So this should be a feature request for the original js-beautify instead of a sublime plugin issue
