### ISSUE TITLE
#include problem

### ISSUE THREAD

**Issue by Trevor2** [victorporof/Sublime-HTMLPrettify#340]
Hi

Thank you very much for your excellent package.
I have 1 problem with it.
My code contains
`#include someFile.js`
in it. the '#' is part of Adobe's jsx script.
Prettify is separating the # from the include with a new line.
It becomes
      `#`
`include`
I have to manually delete the line break each time prettify runs.
Is there some setting to help me out with this?

Thanks,

Trevor

**Comment by victorporof** [comment]
Please file this bug at https://github.com/beautify-web/js-beautify
