### ISSUE TITLE
HTML attribute alignment

### ISSUE THREAD

**Issue by Narven** [victorporof/Sublime-HTMLPrettify#342]
hi

This is more like a question than a issue. Is it possible to indent and align html attributes like this:

``` html
<badge
  if.bind="username"
  url="/${username}"
  cover.bind="item.team.cover"
  default-cover.bind="defaultCover"
  title.bind=".title"
  tagline.bind="tagline">
</badge>
```

thanks

**Comment by amorek** [comment]
+1
I'm also looking forward for attributes alignement. I don't think it's currently possible.

**Comment by victorporof** [comment]
Please file this bug at https://github.com/beautify-web/js-beautify

**Comment by w3cay** [comment]
Add this to  **.jsbeautifyrc**
```
    "html":
    {
        "wrap_attributes": "force",
    },
```

**Comment by victorporof** [comment]
Nice!
