### ISSUE TITLE
Error handling?

### ISSUE THREAD

**Issue by laggingreflex** [victorporof/Sublime-HTMLPrettify#345]
Any errors in `js-beautify` cause it to crash and show the error "Node.js was not found in the default path".

It should actually show the error thrown by js-beautify, like:

```
Error: Invalid Option Value: The option 'operator_position' must be one of the following values
before-newline,after-newline,preserve-newline
You passed in: 'afternewline'
```

**Comment by victorporof** [comment]
Fixed in #374
