### ISSUE TITLE
Not support `{{else if}}` directive in handlebars

### ISSUE THREAD

**Issue by shijistar** [victorporof/Sublime-HTMLPrettify#350]
Thank you very much for such a wonderful plugin! It saves lots of my time in formatting html code in handlebars (.hbs) templates. Everything just works very well however except not supporting `{{else if ...}}` directive. By default the plugin treats `{{else if}}` as a normal inline directive, it should be treated as a block directive just as `{{#if}}` or `{{else}}`. Here is an example in our project:

``` hbs
{{#if (eq states.timelineCallLog.feedType "CallLog")}}
    {{call/log-card callLog=states.timelineCallLog}} {{else if (eq states.timelineCallLog.feedType "im")}} {{webapp/log-im-card imLog=states.timelineCallLog}} {{else if (eq states.timelineCallLog.feedType "ticket")}} {{webapp/log-ticket-card customer=model.lead ticketLog=states.timelineCallLog}}
{{else}}
    {{call/log-card callLog=states.timelineCallLog}}
{{/if}}
```

It should be formatted as:

``` hbs
{{#if (eq states.timelineCallLog.feedType "CallLog")}}        
    {{call/log-card callLog=states.timelineCallLog}}
{{else if (eq states.timelineCallLog.feedType "im")}}
    {{webapp/log-im-card imLog=states.timelineCallLog}}
{{else if (eq states.timelineCallLog.feedType "ticket")}}
    {{webapp/log-ticket-card customer=model.lead ticketLog=states.timelineCallLog}}
{{else}}
    {{call/log-card callLog=states.timelineCallLog}}
{{/if}}
```

This problem confuses us everyday. Whenever I formatted the code by pressing `ctrl+shift+h`, I had to search `{{else if` corrected and re-intended them manually. 

Is it possible be fixed in a soon release? Big thank you again!

**Comment by Zadick** [comment]
I am facing the same trouble using jinja2 (with Flask python framework) in my .html documents.

Actually there is no problem when we use {{ ... }} in pure html code, the trouble is when we use it in javascript code which is inside the html documents.

It is not possible to ignore the {{ starst, the }} stops and everything between them ?

                  Thanks you verify much !

**Comment by victorporof** [comment]
https://github.com/beautify-web/js-beautify
