### ISSUE TITLE
end_with_newline = true inserts 2 new lines at the enf of file

### ISSUE THREAD

**Issue by israelrios** [victorporof/Sublime-HTMLPrettify#351]
When js formatting a file with option "end_with_newline = true" the result will be a file with 2 new lines at the end. This is caused by the use of **console.log** in run.js. Console.log appends a "\n" to the written string. To fix that please use **process.stdout.write** to write the output of run.js.

Thanks.

**Comment by amit1911** [comment]
+1

**Comment by ntv-luke** [comment]
I'm having the same issue here. This is the only thing holding me up.

**Comment by victorporof** [comment]
Fixed in #374
