### ISSUE TITLE
why body ,head, html need one empty line?

### ISSUE THREAD

**Issue by pageye123** [victorporof/Sublime-HTMLPrettify#354]
there is one empty line between <head> and <body> as well as <body> and <head>.

why should seperate them by one line? 
Could you help add options like `seperate_html_body_head` to configure it.

for the code below :
```
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Document</title>
</head>
<body>
</body>
</html>
```
it become this when execute `HTMLPrettify`:
```
<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="UTF-8">
	<title>Document</title>
</head>

<body>
</body>

</html>
```
thx~

**Comment by victorporof** [comment]
Please file this bug at https://github.com/beautify-web/js-beautify
