### ISSUE TITLE
[Bug] Not prettify some .json files

### ISSUE THREAD

**Issue by Kristinita** [victorporof/Sublime-HTMLPrettify#355]
### Summary

I can not prettify some `json` files. HTML and CSS prettifying good for me, but not `json`.

### Expected behavior

I have file `test.json` — <https://gist.github.com/5ab0d4950269bbbf7b2c3943b3945b4e>.

If I use [jsbeautifier.org](http://jsbeautifier.org/) or plugin [CodeFormatter](https://github.com/akalongman/sublimetext-codeformatter) like HTML-Prettify used JSBeautifier, I have expected behavior — <https://gist.github.com/b7b882acbe56feeb9b6ae0e228afbb14>

### Actual behavior

Not prettified file `test.json`.

### Steps to reproduce

The problem is reproduced for me in a version of Sublime Text without plugins and user settings.

I not change HTMLPrettify configuration. Path to my `node.exe` file is correct — `C:/Program Files/nodejs/node.exe`.

In file `test.json` I press <kbd>Ctrl+Shift+P</kbd> → `HTMLPrettify` → my `json` not prettified.

### Environment

**Operating system and version:**
Windows 32-bit 10.0.14393
**Sublime Text:**
Build 3126
**Node.js:**
6.7.0

Thanks.

**Comment by emac** [comment]
I encountered the same issue. The workaround I find is to change "brace_style" from "collapse-preserve-inline" to "collapse" in the plugin preference. Hope it helps.

**Comment by emac** [comment]
I encountered the same issue. The workaround I find is to change "brace_style" from "collapse-preserve-inline" to "collapse" in the plugin preference. Hope it helps.

**Comment by Kristinita** [comment]
@emac , it's worked in `json`, but not worked, for example, in `sublime-settings` files (I set `sublime-settings` extension in `allowed_file_extensions` parameter). CodeFormatter nice prettify `sublime-settings` files.

Thanks.

**Comment by victorporof** [comment]
All you need to do is add `sublime-settings` in the allowed file extensions. See the readme.

**Comment by victorporof** [comment]
#374 makes this a default behavior.
