### ISSUE TITLE
Handling spacebars

### ISSUE THREAD

**Issue by mrkafk** [victorporof/Sublime-HTMLPrettify#356]
Hello,

Could you please add support for Meteor's Spacebars? http://meteorcapture.com/spacebars/

Right now it puts subsequent tags on one line:

    {{/if}} {{/if}}

Yes, theoretically I could add ignore directive in comment around each tag / tag series...

**Comment by victorporof** [comment]
Please file this bug at https://github.com/beautify-web/js-beautify
