### ISSUE TITLE
How to format on save only on html but not js files

### ISSUE THREAD

**Issue by jasjuang** [victorporof/Sublime-HTMLPrettify#358]
This plugin is working great for me so far to autoformat html files, however my problem is I am already using clang-format to autoformat my javascript files and I would like to keep using it. I am not able to figure out how to enable format on save for html files only for this plugin. Any help is appreciated.

**Comment by victorporof** [comment]
You could remove all file extensions defined in `allowed_file_extensions` (see readme for more info). Alternatively, after #374 lands, you could add some regex rules to exclude all js and css files.
