### ISSUE TITLE
Found a problem in less?

### ISSUE THREAD

**Issue by chenweihan** [victorporof/Sublime-HTMLPrettify#362]
.prefix(@style, @value) {
    -webkit-@{style}: @value;
    -moz-@{style}: @value;
    -ms-@{style}: @value;
    -o-@{style}: @value;
    @{style}: @value;
}
after formatting will not compile successfully，can you help me? Thanks

**Comment by victorporof** [comment]
Please file this bug at https://github.com/beautify-web/js-beautify
