### ISSUE TITLE
Settings "wrap_line_length" not working

### ISSUE THREAD

**Issue by leandroluk** [victorporof/Sublime-HTMLPrettify#364]
I've been using the plugin for some time in Sublime Text 3 and I'm having trouble making sure it does not break the lines of code I'm implementing when I'm asked to indent. In the settings of it, I realized that there is the "wrap_line_length" option for either HTML, CSS or JS but regardless if I set the value of that key to 9999 (number) or "9999" (string) or 0 (number) or "0" (string),  it keeps breaking my code when it reaches about 80 characters.

**Comment by victorporof** [comment]
Please file this bug at https://github.com/beautify-web/js-beautify
