### ISSUE TITLE
use currently selected file syntax as opposed to file extension to determine file type

### ISSUE THREAD

**Issue by cachrisman** [victorporof/Sublime-HTMLPrettify#365]
Is it possible to use the currently selected file syntax as opposed to file extension to determine file type?? I'm opening a lot of files that don't have extensions and manually selecting javascript as the syntax, but HTMLPrettify doesn't work unless I save the file with a `.js` extension.

**Comment by victorporof** [comment]
Fixed in https://github.com/victorporof/Sublime-HTMLPrettify/pull/374
