### ISSUE TITLE
Can't undo cmd+z on Mac after save

### ISSUE THREAD

**Issue by gioknx** [victorporof/Sublime-HTMLPrettify#367]
If I hit cmd+z several times and save, I can't use cmd+shift+z to undo them. Anyone knows why?

The only option I changed in format_on_save and I'm using ST3

**Comment by victorporof** [comment]
Is this fixed with the latest release? (2.0.5)

**Comment by victorporof** [comment]
Closing this for now as I am unable to reproduce.
