### ISSUE TITLE
HTML prettify breaks code with spaces

### ISSUE THREAD

**Issue by emanuel1025** [victorporof/Sublime-HTMLPrettify#372]
HTML prettify modifies below code from:

` <select id="mentoringGrade" multiple="multiple" ng-model="userMentoringGrade">
                                            <option value="1">1</option>
                                            <option value="2">2</option>
                                            <option value="3">3</option>
                                            <option value="4">4</option>
                                            <option value="5">5</option>
                                            <option value="6">6</option>
                                            <option value="7">7</option>
                                            <option value="8">8</option>
                                            <option value="9">9</option>
                                            <option value="10">10</option>
                                            <option value="11">11</option>
                                            <option value="12">12</option>
                                        </select>`

to: 

`<select id="mentoringGrade " multiple="multiple " ng-model="userMentoringGrade ">
                                            <option value="1 ">1</option>
                                            <option value="2 ">2</option>
                                            <option value="3 ">3</option>
                                            <option value="4 ">4</option>
                                            <option value="5 ">5</option>
                                            <option value="6 ">6</option>
                                            <option value="7 ">7</option>
                                            <option value="8 ">8</option>
                                            <option value="9 ">9</option>
                                            <option value="10 ">10</option>
                                            <option value="11 ">11</option>
                                            <option value="12 ">12</option>
                                        </select>`

This leads to incorrect values sent to the server. This only happens when I try to prettify the entire page and does not happen if I prettify just the above text. Maybe values, ids and classes should be left as is?

**Comment by wishinghand** [comment]
I have something similar happening to LESS files.

This line:
`@media (max-width: 700px) {...}`

gets changed to:

`@media(max - width: 700 px) {...}`

It happens to class names, CSS properties (`font-size`), and CSS values (`inline-block`).

**Comment by rommmka** [comment]
Same problem here:
```html
<li class="item"><a href="{{store url="updates"}}">Updates</a></li>
```
changed to:

```html
<li class="item"><a href="{{store url=" updates "}}">Updates</a></li>
```
That's breaking markup.

**Comment by MateuszDabrowski** [comment]
Bump.

```
<input name="WKPL-LAW-ElectronicProducts" type="checkbox" value="on" data-subscription="<eloqua type='subscriptionstatus' groupId='42'/>"/>
```
changes to 

```
<input name="WKPL-HRSAFETY-ElectronicProducts" type="checkbox" value="on" data-subscription="<eloqua type='subscriptionstatus' groupId='45' />
"  />
```

Which not only adds unneeded spaces but also brakes indentation, which in sublime means that I cannot fold code properly.

**Comment by victorporof** [comment]
Please file this bug at https://github.com/beautify-web/js-beautify

**Comment by Manuman169** [comment]
Now it happens to me. From this bad code:
`div#item {
    width:    auto   ;
    height: 100    px;
    background-color: red   ;
    margin: 0 auto   ;
    border-radius: 4    px    ;
}`

Go to this one, which has spaces before "px":
`div#item {
    width: auto;
    height: 100 px;
    background-color: red;
    margin: 0 auto;
    border-radius: 4 px;
}`
