### ISSUE TITLE
How to keep break lines?

### ISSUE THREAD

**Issue by Luc45** [victorporof/Sublime-HTMLPrettify#379]
Line breaks are part of the semantics of my code, I don't want to remove them on prettify.

Example of code where I don't want to remove line breaks:

`
<div class="col-sm-8 blog-main">

	<h1>Some title</h1>
	<main>Some content</main>

	<hr>

	<div class="comments">Something here</div>

</div>
`

Can I toggle the feature of removing empty lines on the plugin settings?

**Comment by victorporof** [comment]
Please file this issue at https://github.com/beautify-web/js-beautify
