### ISSUE TITLE
space_after_function

### ISSUE THREAD

**Issue by lipengzhou** [victorporof/Sublime-HTMLPrettify#383]
Can you add "space_after_function"    (not space_after_anon_function).

like "space_after_function":

```javascript
function fn () {
  console.log('Hello World')
}
```

"space_after_anon_function":

```javascript
function fn() {
  console.log('Hello World')
}
```

Thanks.

**Comment by victorporof** [comment]
Please file this issue at https://github.com/beautify-web/js-beautify

**Comment by dylan-munro** [comment]
Just reopening this -- it looks like they have ""space_after_named_function" as an attribute. Would that fix this? I too, would like to be able to define my functions with a space after them. 

It doesn't seem to work with the Prettify settings files as is. Is that something you need to add?

**Comment by ns412** [comment]
Just reopening this -- it looks like they have ""space_after_named_function" as an attribute. Would that fix this? I too, would like to be able to define my functions with a space after them.

It doesn't seem to work with the Prettify settings files as is. Is that something you need to add?

**Comment by victorporof** [comment]
You can add it into your jsbeautifyrc settings and it will be respected.
