### ISSUE TITLE
I can't pretify code when use in Sublime Text 3

### ISSUE THREAD

**Issue by pnlinh** [victorporof/Sublime-HTMLPrettify#386]
![crash](https://user-images.githubusercontent.com/26193890/28235677-eec3b09a-693c-11e7-8bea-4b33578a0056.png)

Can you help me ? Thank you.

**Comment by SSimbah** [comment]
me too

**Comment by victorporof** [comment]
What is the output in sublime's console when the error occurs?

**Comment by vinaynb** [comment]
Same issue. 10 machines using this plugin in ST3 stopped working since this morning. Seems like the latest release is causing this.

Here is the error in console @victorporof 
```
const assign = require('./util/assign')
^^^^^
SyntaxError: Use of const in strict mode.
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/home/upc1/.config/sublime-text-3/Packages/HTML-CSS-JS Prettify/build/js-transpiled/main.js:127:16)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
```

**Comment by victorporof** [comment]
What node version are you using?

**Comment by vinaynb** [comment]
6.4.0

**Comment by pnlinh** [comment]
![crash2](https://user-images.githubusercontent.com/26193890/28237215-70a29528-6964-11e7-9fb7-fd726643af66.png)

My sublime console.

**Comment by victorporof** [comment]
Does this still happen in version 2.0.6 (released yesterday)? You can check the plugin's version by looking into the package.json file inside the plugin's directory.

**Comment by victorporof** [comment]
@vinaynb Does updating to latest node (8.1.4) fix the issue?

**Comment by vinaynb** [comment]
@victorporof nope it does not. Tried using with node 8.1.4 via nvm

**Comment by pnlinh** [comment]
@victorporof I'm using version 2.0.6.

**Comment by victorporof** [comment]
@vinaynb Is the node path specified in the plugin's settings the path to the 8.1.4. version?

**Comment by vinaynb** [comment]
@victorporof ok it was pointing to wrong node path. Fixed to the path used by nvm and it works now but the indentation has gone for a toss (its using lot more tabs which it wasn't using before). Any idea what do i need to change for this ?

**Comment by vinaynb** [comment]
@victorporof also can you specify the minimum node version required for this plugin to work ?

**Comment by victorporof** [comment]
@vinaynb Theoretically this should work with 4.0.0+. What was the old node version which didn't work in your case?

**Comment by victorporof** [comment]
@vinaynb When it comes to the formatting issues, can you provide your .jsbeautifyrc, .editorconfig (if you use it), and the plugin settings json?

**Comment by victorporof** [comment]
@pnlinh If you update your node and make sure the node path is correct, does the issue persist?

**Comment by vinaynb** [comment]
@victorporof it was previously working in 6.4.0 as well as 0.10.25. This morning it didn't work in both. Guess previously it somehow used to get the correct node path but after update it doesn't  and we need to supply manually. My machines are all ubuntu 14.04 btw

**Comment by victorporof** [comment]
Yes, the old version did work in node 0.10.25, but that was a version of this plugin that tried to maintain compatibility with insanely old node versions. We've dropped this with the release of 2.0, and reasonably recent versions of node are required (at least ones which aren't almost 4 years old).

**Comment by vinaynb** [comment]
@victorporof ok. Thanks for the help. Appreciated :)

**Comment by yashvekaria** [comment]
@victorporof @vinaynb , your conversation, helped me to resolve my same case. Thanks Great help.

**Comment by victorporof** [comment]
@yashvekaria What was the console output in your case? Very curious to see if we can streamline this process and avoid any such new issues being filed.

**Comment by victorporof** [comment]
Pushed a proactive measure for this issue: https://github.com/victorporof/Sublime-HTMLPrettify/commit/4c49c153119ec463022fd0b52a8d69b3c36e18a9

New release 2.0.7 automatically tracks this problem and suggests updating node to a reasonably recent version, as well as making sure the path to this updated node is correctly set in this plugin's settings.

**Comment by victorporof** [comment]
@vinaynb Have you figured out the tab length issue?

**Comment by vinaynb** [comment]
no not yet. I am looking into it. Looks like previously the plugin was not using my .editorconfig but now it is being used. I guess i need to look into it more deeper to confirm the exact issue. Will update as soon as i have something.

**Comment by victorporof** [comment]
Thanks! Support for editorconfig files was added in version 2 due to popular demand. You can turn this off in the plugin options (see readme).

**Comment by victorporof** [comment]
@pnlinh Is your issue fixed?

**Comment by pnlinh** [comment]
@victorporof Still bug 
![crash3](https://user-images.githubusercontent.com/26193890/28239255-096697aa-6992-11e7-98b8-1de11b8b72de.png)

**Comment by victorporof** [comment]
@pnlinh What is the plugin's options file looking like?

**Comment by pnlinh** [comment]
List of plugins in my Sublime Text 3

![screenshot 2017-07-15 20 01 06](https://user-images.githubusercontent.com/26193890/28239525-73329aac-6998-11e7-9bc2-f3d7e45fa1cf.png)

**Comment by victorporof** [comment]
@pnlinh I'm asking for something else. What settings do you see when clicking on Plugin Options - Default and User?

**Comment by pnlinh** [comment]
@victorporof I'm sorry. It's here
![crash4](https://user-images.githubusercontent.com/26193890/28239574-67ff2b9a-6999-11e7-905f-9a7003584572.png)

**Comment by victorporof** [comment]
@pnlinh Still not what I'm asking for. This plugin's settings file, not sublime's settings.

**Comment by pnlinh** [comment]
@victorporof I found the cause. I install NodeJS is OK. Thank so much

**Comment by vinaynb** [comment]
@victorporof below is my editorconfig file
```
# EditorConfig helps developers define and maintain consistent
# coding styles between different editors and IDEs
# editorconfig.org

root = true


[*]

# Change these settings to your own preference
indent_style = tab
indent_size = 4

# We recommend you to keep these unchanged
end_of_line = lf
charset = utf-8
trim_trailing_whitespace = true
insert_final_newline = true

[*.md]
trim_trailing_whitespace = false
```

What happens is that when a js file is opened the existing default indentation is with tabs and tab_size=4 but as soon as i beautify it with this plugin it multiplies each existing tab indentation with 4. 
i.e. if a line was indented previously with a 1 tab of length 4 now it will be indented with 4 tabs of length 4.

Why does it does not take into account the existing indentation ? As previously my projects were not using .editorconfig the indentation was not uniform. How do i convert all my existing source into tabs with length 4 and avoid this plugin from messing them up ?

**Comment by victorporof** [comment]
I don't think this is an issue with the plugin. The way I understand this, you're settings say "indent with 4 tabs". If it was previously 4 spaces, each space becomes a tab, which I would expect.

What you should probably do is set the tab size in sublime to determine how wide a tab is displayed. Otherwise, try "convert indentation to tabs" in sublime.

**Comment by victorporof** [comment]
I would imagine
```
indent_style = tab
indent_size = 1
```
is the equivalent of
```
indent_style = space
indent_size = 4
```

If you mix these up, I think it's expected to get the results you're describing.

**Comment by vinaynb** [comment]
@victorporof Maybe you can guide me a little here 
There is an existing file and i opened it in sublime and converted indentation to tabs (tab_size=4). It appears nicely indented as below 

```
(function() {
	'use strict';  //this line is indented by 1 tab of width=4
	
	angular.module('assessment', [
		'vendor',
		'layouts',
		'shared',
		'dashboard',
	]);

})();
```

Now i run the plugin and prettify it and result is as follows 
```
(function() {
				'use strict';       //this line is indented now by 4 tabs of width=4

				angular.module('assessment', [
								'vendor',
								'layouts',
								'shared',
								'dashboard',
				]);

})();
```

**Comment by victorporof** [comment]
You want
```
indent_style = tab
indent_size = 1
```
in your editorconfig.
