### ISSUE TITLE
can't prettify the long html code

### ISSUE THREAD

**Issue by blyk** [victorporof/Sublime-HTMLPrettify#387]

**Comment by victorporof** [comment]
Does this still happen in version 2.0.6 (released yesterday)?

**Comment by victorporof** [comment]
Can you please provide the output in sublime's console? Any specific steps to reproduce this issue? Which Sublime version are you using?

**Comment by victorporof** [comment]
I'm making this a duplicate of https://github.com/victorporof/Sublime-HTMLPrettify/issues/380

If this still happens in version 2.0.6, please reopen and provide more information.

**Comment by blyk** [comment]
Hey, I updated the plugin and it is fixed now :) thanks @victorporof
