### ISSUE TITLE
HI guys, anyone can resolve this problem

### ISSUE THREAD

**Issue by yezhanpeng201314** [victorporof/Sublime-HTMLPrettify#391]
# Make sure these boxes are checked before submitting your issue:
- [x] Have you installed the most recent version of Node.js? (8.0.0+)
- [x] Is the Node.js path in the "Plugin Options" pointing to the most recent version of Node.js?

### Desired behavior
What is the desired behavior? What should happen but doesn't?

**Please note by far the quickest way to get a new feature is to file a Pull Request.**

### Expected behavior
What is the expected behavior? What should happen but doesn't?

### Actual behavior
What's happening instead of the expected behavior? A screenshot or a detailed explanation would be useful!

### Steps to reproduce the behavior
How can someone else run into the same issue?

### Environment
Please include the following info: 
* Your custom .jsbeautifyrc file(s) if they exist
* Your custom .editorconfig file(s) if they exist
* Your "Prettify Preferences" Default/User file(s) 
* Your "Plugin Options" Default/User file(s)
* This plugin's version (which you can find in the package.json file under the installation directory)
* Your node version and installation path
* The file you intended to prettify

**Please note by far the quickest way to get a bug fixed is to file a Pull Request.**

**Comment by victorporof** [comment]
You haven't provided any actual meaningful information. I'm closing this issue.

**Comment by victorporof** [comment]
Updating to the latest version https://github.com/victorporof/Sublime-HTMLPrettify/releases will help you better figure out what's going wrong.

I'd still appreciate some meaningful bug report, but if everything else still goes wrong, you can revert to the latest stable version 1.0.0

**Comment by yezhanpeng201314** [comment]
Thank you very much

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: Victor Porof<mailto:notifications@github.com>
发送时间: 2017年7月17日 14:36
收件人: victorporof/Sublime-HTMLPrettify<mailto:Sublime-HTMLPrettify@noreply.github.com>
抄送: yezhanpeng<mailto:yezhanpeng@outlook.com>; Author<mailto:author@noreply.github.com>
主题: Re: [victorporof/Sublime-HTMLPrettify] HI guys, anyone can resolve this problem (#391)


Updating to the latest version https://github.com/victorporof/Sublime-HTMLPrettify/releases will help you better figure out what's going wrong.

I'd still appreciate some meaningful bug report, but if everything else still goes wrong, you can revert to the latest stable version 1.0.0

―
