### ISSUE TITLE
An error occured while using html-prettify command!

### ISSUE THREAD

**Issue by Jacob-Yuan** [victorporof/Sublime-HTMLPrettify#393]
How  to solve this ? My Node.js Version is 4.4.6.

![1](https://user-images.githubusercontent.com/23224565/28238213-76a9d842-6981-11e7-9840-57634add641b.png)

![2](https://user-images.githubusercontent.com/23224565/28238226-a4d2e22c-6981-11e7-91c8-c214e16dd269.png)

**Comment by victorporof** [comment]
Please include more information. I cannot do anything based on what little you provided. See the issue template.

**Comment by victorporof** [comment]
https://github.com/victorporof/Sublime-HTMLPrettify/blob/master/ISSUE_TEMPLATE.md

**Comment by victorporof** [comment]
Please reopen this issue if the steps described in the above link don't help you.

**Comment by victorporof** [comment]
Updating to the latest version https://github.com/victorporof/Sublime-HTMLPrettify/releases will help you better figure out what's going wrong.

I'd still appreciate some meaningful bug report, but if everything else still goes wrong, you can revert to the latest stable version 1.0.0
