### ISSUE TITLE
nodejs

### ISSUE THREAD

**Issue by tranmaianh** [victorporof/Sublime-HTMLPrettify#396]
# Make sure these boxes are checked before submitting your issue:
- [x] Have you installed the most recent version of Node.js? (8.0.0+)
- [x] Is the Node.js path in the "Plugin Options" pointing to the most recent version of Node.js?

** This issue will be automatically deleted if the information detailed below isn't provided.**

### What is your environment?
Please include as much as you can of the following:
* Sublime Text version
* Sublime console output (View -> Show Console)
* Node.js version and real installation path
* Any custom .jsbeautifyrc file(s)
* Any custom .editorconfig file(s)
* Your "Prettify Preferences" Default/User file(s) 
* Your "Plugin Options" Default/User file(s)
* This plugin's version (which you can find in the package.json file under the installation directory)
* The file you intended to prettify

### Expected behavior
What is the expected behavior? What should happen but doesn't?

### Actual behavior
What's happening instead of the expected behavior? A screenshot or a detailed explanation would be useful!

### Steps to reproduce the behavior
How can someone else run into the same issue? How can the developers of this plugin encounter the same issue?

### If this is a feature request regarding prettification rules and code style, please file it here: https://github.com/beautify-web/js-beautify

**Please note by far the quickest way to get a new feature is to file a Pull Request.**

**Comment by victorporof** [comment]
Please read the above instructions and provide the information requested, otherwise I cannot act on this bug.

**Comment by victorporof** [comment]
Updating to the latest version https://github.com/victorporof/Sublime-HTMLPrettify/releases will help you better figure out what's going wrong.

I'd still appreciate some meaningful bug report, but if everything else still goes wrong, you can revert to the latest stable version 1.0.0
