### ISSUE TITLE
With MongoDB

### ISSUE THREAD

**Issue by goodgoodwish** [victorporof/Sublime-HTMLPrettify#398]

**Comment by victorporof** [comment]
What exactly is the feature request? What about mongoDB?

**Comment by victorporof** [comment]
Please reopen with a more detailed report.

**Comment by goodgoodwish** [comment]
I guess it caused by ES6 => fat arrow syntax.  It's not supported in Prettify.

**Comment by victorporof** [comment]
Please file formatting issues at https://github.com/beautify-web/js-beautify
