### ISSUE TITLE
Unknown erro while prettifying!

### ISSUE THREAD

**Issue by Devil-Cherry** [victorporof/Sublime-HTMLPrettify#402]

**Comment by victorporof** [comment]
To get help, you must provide the following information:

Have you installed the most recent version of Node.js (8.0.0+)?
Is the Node.js path in the "Plugin Options" pointing to the most recent version of Node.js?
What Sublime Text version are you using?
What is the console output when prettifying? (View -> Show Console)
What is your node.js version and real installation path?
Any custom .jsbeautifyrc files?
Any custom .editorconfig files?
What are your "Prettify Preferences" Default/User file contents?
What are your "Plugin Options" Default/User file contents?
What version of this plugin are you using (which you can find in the package.json file under the installation directory)?
What file are you trying to prettify?

Please reopen after providing the required details.

**Comment by victorporof** [comment]
Updating to the latest version https://github.com/victorporof/Sublime-HTMLPrettify/releases will help you better figure out what's going wrong.

I'd still appreciate some meaningful bug report, but if everything else still goes wrong, you can revert to the latest stable version 1.0.0

**Comment by victorporof** [comment]
This is likely a duplicate of https://github.com/victorporof/Sublime-HTMLPrettify/issues/442
Marking it as such for bookkeeping.
