### ISSUE TITLE
emmet

### ISSUE THREAD

**Issue by ljy0916** [victorporof/Sublime-HTMLPrettify#426]

**Comment by victorporof** [comment]
Please file prettification feature requests at https://github.com/beautify-web/js-beautify

**Comment by victorporof** [comment]
Updating to the latest version https://github.com/victorporof/Sublime-HTMLPrettify/releases will help you better figure out what's going wrong.

I'd still appreciate some meaningful bug report, but if everything else still goes wrong, you can revert to the latest stable version 1.0.0
