### ISSUE TITLE
An unhandled error was encountered while prettifying.

### ISSUE THREAD

**Issue by wengdongyang** [victorporof/Sublime-HTMLPrettify#428]

**Comment by ZhangEryi** [comment]
![qq 20170717151630](https://user-images.githubusercontent.com/26322447/28258232-ae344838-6b02-11e7-85a7-bd2b0c2320bc.jpg)

**Comment by victorporof** [comment]
@wengdongyang Can you please tell me what the console output was when the errors were occuring? Thanks!

**Comment by victorporof** [comment]
This is likely a duplicate of https://github.com/victorporof/Sublime-HTMLPrettify/issues/442
Marking it as such for bookkeeping.

**Comment by wengdongyang** [comment]
Thank you .I've solved the problem, apparently because 'nodejs' .I reinstall it(nodejs).

At 2017-07-17 20:36:47, "Victor Porof" <notifications@github.com> wrote:


@wengdongyang Can you please tell me what the console output was when the errors were occuring? Thanks!

**Comment by wengdongyang** [comment]
Thank you .I've solved the problem, apparently because 'nodejs' .I reinstall it(nodejs).

在 2017-07-17 15:34:01，"Victor Porof" <notifications@github.com> 写道：


Closed #428.
