### ISSUE TITLE
Top level ungrouped rules in`.jsbeautifyrc` are ignored 

### ISSUE THREAD

**Issue by ryanpcmcquen** [victorporof/Sublime-HTMLPrettify#434]
I have one setup for the package (`~/Library/Application Support/Sublime Text 3/Packages/User/.jsbeautifyrc`), one in my home directory `~/.jsbeautifyrc`, and one in the top level project folder as well. Yet despite all that, the `jslint_happy` setting is being ignored and `function()` is not being converted to `function ()`.

Mac OS 10.12.x & Sublime Text 3 build 3126.

**Comment by victorporof** [comment]
Can you post your configs? I'll take a look.

**Comment by ryanpcmcquen** [comment]
Certainly!

The one in my home folder and the top level project directory is:

```
{
    "indent_size": 4,
    "indent_with_tabs": false,
    "jslint_happy": true,
    "wrap_line_length": 0
}
```

The one in `~/Library/Application\ Support/Sublime\ Text\ 3/Packages/User/.jsbeautifyrc` is:
```
{
    "jslint_happy": true
}
```

**Comment by victorporof** [comment]
This seems like a jsbeautify issue, please file this bug at https://github.com/beautify-web/js-beautify/issues/15

I can confirm that in this plugin, jsbeautifyrc files are properly extended, however jslint_happy seems to be ignored by the underlying prettifier lib.

**Comment by ryanpcmcquen** [comment]
Sorry, but it isn't. I can run the same code through the beautifier here:

http://jsbeautifier.org/

And `function()` becomes `function ()`.

Same goes for the `atom-beautify` plugin which uses `js-beautify`.

https://atom.io/packages/atom-beautify

**Comment by victorporof** [comment]
Why would some rules get extended and some not?

**Comment by victorporof** [comment]
Oh, I see what's happening. You need to put your rules inside a "js" or "all" key in a jsbeautifyrc, for example: 
"js": {
  "jslint_happy": true
}

**Comment by victorporof** [comment]
I'm reopening this with a different title

**Comment by ryanpcmcquen** [comment]
@victorporof I like the new name. So that would look like this?

```json
{
    "js":
    {
        "jslint_happy": true
    }
}
```

Correct?

**Comment by victorporof** [comment]
@ryanpcmcquen yes!

**Comment by victorporof** [comment]
Can you please post all of your jsbeautifyrc configs and the output in sublime’s console?

**Comment by ryanpcmcquen** [comment]
I have only updated the `Prettify Preferences - User` as shown above, but here is the console output:

https://gist.github.com/ryanpcmcquen/e81baac4a07b4e1b8363273cc0416fa2

As you can see, `jslint_happy` comes out as `false` in the computed options.

**Comment by victorporof** [comment]
I cannot reproduce this. I've tried doing what you suggested: creating a .jsbeautifyrc config file in the home folder, with the following contents:
```js
{
    "js":
    {
        "jslint_happy": true
    }
}
```

The sublime console's output properly shows `jslint_happy` as being true.

I'm not entirely sure what's going on. Can you please simply post the .jsbeautifyrc files under `Attempting to parse file` in the above gist?
