### ISSUE TITLE
出错

### ISSUE THREAD

**Issue by hmhbhd** [victorporof/Sublime-HTMLPrettify#437]
出错

**Comment by JasonMgz0411** [comment]
你该抛出错误

**Comment by xllily** [comment]
![image](https://user-images.githubusercontent.com/13611125/28296638-035acf78-6b9c-11e7-9b43-4533b748f964.png)
How to fix?

**Comment by tracyvon** [comment]
我也有一样的错误,后面看了下nodejs路径,才发现路径不对,改了就正常了.

**Comment by victorporof** [comment]
Duplicate of https://github.com/victorporof/Sublime-HTMLPrettify/issues/440
