### ISSUE TITLE
2.0.10 In css adds new lines above all comments each time css it's prettified 

### ISSUE THREAD

**Issue by inflonet** [victorporof/Sublime-HTMLPrettify#451]
Everytime time a css file it's prettified a new line it's added above comments. Exception is made for commented css rules and if there is a comment on the first line in the file. So if you prettify a css file 5 times you end up with 5 line breaks above each comment in the file.

/*----------------------someCss------------------------*/

.someCss {
    padding-top: 5px;
    padding-left: 5px;
    display: inline-block;
    /*padding-bottom: 0px;*/
}
<br>
<br>
<br>
<br>
<br>
/*----------------------anotherCss------------------------*/

.anotherCss {
    padding-top: 5px;
    padding-left: 5px;
    display: inline-block;
    padding-bottom: 0px;
}

**Comment by victorporof** [comment]
Please file this at https://github.com/beautify-web/js-beautify/blob/master/jsbeautifyrc
