### ISSUE TITLE
Syntax errors in .jsbeautifyrc user config

### ISSUE THREAD

**Issue by ssmalltone123** [victorporof/Sublime-HTMLPrettify#452]
![hw9 mc91ln2h96qn9 _4](https://user-images.githubusercontent.com/26520592/28317466-9dd2745e-6bf9-11e7-9cd9-ef924f08bd48.png)
![pl q1ail_1q g mh 2_o u](https://user-images.githubusercontent.com/26520592/28317470-a262922e-6bf9-11e7-8e1e-9ee069b612db.png)

**Comment by victorporof** [comment]
What are the contents of your user .jsbeautifyrc?

**Comment by explorador** [comment]
Same error here, here are my contents:
https://codeshare.io/2EMP08

**Comment by victorporof** [comment]
Your jsbeautifyrc file isn't proper json. You can clearly see this under `    "indent_char": " ",r`, the "r" shouldn't be there.
