### ISSUE TITLE
New blank lines in CSS while prettifying with comments

### ISSUE THREAD

**Issue by s-tsarenko** [victorporof/Sublime-HTMLPrettify#453]
I have comments in my CSS like this
/*======Some Text======*/
After first prettifying I have 2 blank lines before comment, after second prettifying — 3 lines, third — 4… 
The number of blank lines grow up after every prettify command.

**Comment by s-tsarenko** [comment]
sorry, found solution here https://github.com/victorporof/Sublime-HTMLPrettify/issues/451

**Comment by Boycce** [comment]
What was your solution? Or do you mean _sorry_ wrong project for your issue?

**Comment by Boycce** [comment]
Anyone else needing a temporary solution, for this bug renders this plugin useless in my case, install [1.0](https://github.com/victorporof/Sublime-HTMLPrettify/releases/tag/1.0) into your Packages directory.

**Comment by victorporof** [comment]
You can also try to update jsbeautify inside the plugin's build directory to a later version (if it exists)
