### ISSUE TITLE
[WinError 6] The handle is invalid

### ISSUE THREAD

**Issue by AVD087** [victorporof/Sublime-HTMLPrettify#455]
Hello There,

Even i have installed node in default path, i'm receiving now below error in console whenever i try to preetify.

[WinError 6] The handle is invalid

**Comment by victorporof** [comment]
Can you please post the output in sublime's console?

**Comment by victorporof** [comment]
@AVD087 Can you please post the entire output in sublime's console?

**Comment by AVD087** [comment]
I only receive this error in console , nothing else.

`[WinError 6] The handle is invalid`

**Comment by victorporof** [comment]
What is your sublime version?

**Comment by victorporof** [comment]
Are you getting a prompt about unhandled errors when you try to prettify?

**Comment by AVD087** [comment]
I'm using Sublime text 3 and getting below prompt.

**An unhandled OS error was encountered while prettifying.
This usually means Node.js was not found in the default path.
Please specify the location.**

**Comment by AVD087** [comment]
Similar to issue #461 it used to work before with the same configuration.

**Comment by victorporof** [comment]
Have you tried setting the correct path to node.js in the plugin’s settings?

**Comment by victorporof** [comment]
What is your node path out of curiosity?

**Comment by AVD087** [comment]
Yes , i check many times , and node is at it's default windows path `C:/Program Files/nodejs/node.exe` same set in configuration.

displays same for `where node`.

is there any node package that i should check for or it relates to sublime text?

**Comment by AVD087** [comment]
`htmlprettify` doesn't work directly in cmd if that's the package which runs it.

**Comment by victorporof** [comment]
Did this plugin ever work for you or is it happening after an update?

**Comment by AVD087** [comment]
I guess it's after update. It was working before.

**Comment by victorporof** [comment]
I'm quite lost here. I'm unable to reproduce this `[WinError 6] The handle is invalid` issue, and it doesn't seem related to https://github.com/victorporof/Sublime-HTMLPrettify/issues/454 at all (the one you suspected in https://github.com/victorporof/Sublime-HTMLPrettify/issues/455#issuecomment-318579609

**Comment by victorporof** [comment]
(didn't mean to close)

**Comment by victorporof** [comment]
@AVD087 Does this help? b661daf73b08de1c054efd66b8699f196cbe5588

**Comment by cforelle** [comment]
This is fixed for me in 2.1.3
thanks!

**Comment by victorporof** [comment]
Wohoo!

**Comment by AVD087** [comment]
Fixed for me too..
Great work, Thanks !!! :)
