### ISSUE TITLE
Node path not set

### ISSUE THREAD

**Issue by Dalton123** [victorporof/Sublime-HTMLPrettify#464]

**Comment by cforelle** [comment]
I also have this problem, despite the path actually appearing to be set correctly. This is a relatively recent development. 
![image](https://user-images.githubusercontent.com/10046979/28829340-48e27ae8-76cb-11e7-9247-0784f80b3039.png)

**Comment by victorporof** [comment]
What is the output in sublime's console?

**Comment by cforelle** [comment]
`Using node.js path on 'windows': C:/Program Files/nodejs/node.exe`
`Unexpected error(<class 'OSError'>): [WinError 6] The handle is invalid`

**Comment by victorporof** [comment]
Ok, so this is a duplicate of #455
