### ISSUE TITLE
1 empty row in html is removed and a bit slow

### ISSUE THREAD

**Issue by vitaliyterziev** [victorporof/Sublime-HTMLPrettify#466]
It seems that all is working as expected with the exception of a tiny lag before formatting the code and removing the blank rows between html elements

**Comment by victorporof** [comment]
Please file the blank row removal issue at https://github.com/beautify-web/js-beautify

**Comment by vitaliyterziev** [comment]
the problem is not there.. http://jsbeautifier.org/ is not doing it

**Comment by victorporof** [comment]
Formatting issues need to be filed there. Speed issues here.
