### ISSUE TITLE
How to remove the blank space b/w every css rule?

### ISSUE THREAD

**Issue by icookcode** [victorporof/Sublime-HTMLPrettify#474]
I tried with changing value from True to False on below line but no luck.

// Add a new line after every css rule
        "newline_between_rules": false,

Referring to these spaces - http://i.imgur.com/1qQknXd.png

Also wanted to ask if it's possible to put the comment in HTML to appear on same line where </div> end instead of new line.

Referring to these comments - http://i.imgur.com/b1myjTg.png

**Comment by victorporof** [comment]
This is an issue in the jsveautify library, not this plugin. Please file there instead. thank you!
