### ISSUE TITLE
Found a bug in the CSS format?

### ISSUE THREAD

**Issue by chenweihan** [victorporof/Sublime-HTMLPrettify#475]
Hi： 
   if the css format hava /\*\*,  when every time save, it will generate a new line.
   style on Sublime-HTMLPrettify v2.0
   eg:
   /\*\*\* test***/
   .test{}
   ( generate new line when every time save it)
   /*** test1 ***/
   .test1{}

**Comment by jdiponziano** [comment]
I've got the same issue! Any fixes for this? Super annoying and lots of crazy spacing in my css file

**Comment by mike-v-l** [comment]
same issue, very annoying.  Lover the app btw, thank you for your work.

**Comment by juliomoreira** [comment]
Same here.

**Comment by MisketAdam** [comment]
I've come here to look for a solution to this. And...

**Comment by victorporof** [comment]
This seems to be an issue in https://github.com/beautify-web/js-beautify, please file there. Thank you!
