### ISSUE TITLE
Suggesting a different plugin name

### ISSUE THREAD

**Issue by hced** [victorporof/Sublime-HTMLPrettify#48]
First off, thanks for a great plugin! I appreciate it greatly.

As a suggestion, I think it would be better if it was called something else than `HTMLPrettify`, to reflect that it operates on CSS and JS files as well.

For example, either removing the HTML part of the name or replacing it with something else and keep the Prettify part... Right now, while editing a JS file, it's not too obvious that you can prettify it with `HTMLPrettify` command.

**Comment by victorporof** [comment]
At this point, I don't think it matters anymore, and there's a lot of places linking to this particular plugin name, or referring to it as such.
