### ISSUE TITLE
Does Not Work On Syntax Error

### ISSUE THREAD

**Issue by lnorton89** [victorporof/Sublime-HTMLPrettify#481]
After an hour of trying to figure out why the plugin was not working in one file it seems an h4 tag was closed with an h5 tag. Is there anyway the plugin could inform the user of this via the console instead of just not working at all with zero feedback as to why?

**Comment by victorporof** [comment]
Can you please post the output in sublime's console. What you're saying should indeed be possible, but it seems like the underlying prettifier lib is throwing an error, which we should handle more gracefully.

**Comment by Muddassir1171** [comment]
It will help you if i got your problem then Install Packages * Highlight Build Error & Sublime Text Linter for PHP and others.

**Comment by victorporof** [comment]
Please file this issue at https://github.com/beautify-web/js-beautify

However, I'm not sure if prettying with syntax errors is desirable or not. I'll let the prettifier library author decide.
