### ISSUE TITLE
libicui18n.58.dylib not loaded on initial run

### ISSUE THREAD

**Issue by reilly3000** [victorporof/Sublime-HTMLPrettify#484]
Node.js encountered a runtime error: dyld: Library not loaded: /usr/local/opt/icu4c/lib/libicui18n.58.dylib
  Referenced from: /usr/local/bin/node
  Reason: image not found

I'm running SublimeText 3 Build 3143 on MacOS 10.12.6. I just was installing this plugin for the first time and keep getting this error upon trying to run the html prettify command.

**Comment by victorporof** [comment]
What is your node version?

**Comment by reilly3000** [comment]
It was indeed out of date, not exactly sure of the previous version but I believe it was 8.0.12. Updating to 8.5.0 fixed the issue.
