### ISSUE TITLE
HTML Prettify has issue of adding spaces behind "class" and "id"

### ISSUE THREAD

**Issue by cheneus** [victorporof/Sublime-HTMLPrettify#486]
Unwanted space behind the value of class and ids added after using the plugin. 

Look at the screenshot that I have took from before/after. 
![screenshot_20170921_202617](https://user-images.githubusercontent.com/11591634/30725588-5f3addcc-9f0b-11e7-8fc9-5c1fd1328ebd.png)

**Comment by victorporof** [comment]
Please file this bug at https://github.com/beautify-web/js-beautify
