### ISSUE TITLE
not working with latest version of sublime text - Sublime Text 3 (Build 3143)

### ISSUE THREAD

**Issue by shamseerahammedm** [victorporof/Sublime-HTMLPrettify#488]

**Comment by h13579** [comment]
It works for me. After installing through **Package Control**, i renamed the folder to be 'Sublime-HTMLPrettify'.
What errors do you get?

**Comment by yisenliu** [comment]
Same here. It's not working with **ST3 build 3143** when I want to prettify **.js** file and there is no errors showed. Even reinstalling this package, it's still not working.

**Comment by victorporof** [comment]
Possibly a dupe of https://github.com/victorporof/Sublime-HTMLPrettify/issues/567 which I'm pushing a fix for today.

Please reopen with more details if not the case.
