### ISSUE TITLE
When trying to prettify jquery-3.2.1.min.js

### ISSUE THREAD

**Issue by MYepiz** [victorporof/Sublime-HTMLPrettify#493]
[jquery-3.2.1.min.zip](https://github.com/victorporof/Sublime-HTMLPrettify/files/1353173/jquery-3.2.1.min.zip)

**Comment by victorporof** [comment]
Can you take a look at the existing issues filed for this plugin? If you can't find something that matches your issues, please reopen with more details if possible.
