### ISSUE TITLE
Not enough information to know how to react/correct

### ISSUE THREAD

**Issue by jeanfontaine** [victorporof/Sublime-HTMLPrettify#496]
<META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=UTF-8">
<div style="clear:both;" id="wrapper">
....

startup time: 0.75561 (package setup was not run)
loaded 837 snippets
Package Control: Skipping automatic upgrade, last run at 2017-10-12 07:42:10, next run at 2017-10-12 08:42:10 or after
'ascii' codec can't encode character u'\xa7' in position 1141: ordinal not in range(128)

**Comment by victorporof** [comment]
Probably a dupe of https://github.com/victorporof/Sublime-HTMLPrettify/issues/442

I don't know how to fix that. Patches welcome!
