### ISSUE TITLE
CSS: it keeps adding a newline before a comment.

### ISSUE THREAD

**Issue by 8lall0** [victorporof/Sublime-HTMLPrettify#504]
When i comment something in my css files, like that
`/* Fira sans */`
It adds a newline before the line, even if there is another newline.

**Comment by danielhickman** [comment]
Related: https://github.com/victorporof/Sublime-HTMLPrettify/issues/492

**Comment by victorporof** [comment]
Dupe of https://github.com/victorporof/Sublime-HTMLPrettify/issues/492
