### ISSUE TITLE
vue files and styl files Prettify Error

### ISSUE THREAD

**Issue by roy-lau** [victorporof/Sublime-HTMLPrettify#508]
**vue in styl：**

![default](https://user-images.githubusercontent.com/22829291/32988410-4cb5125a-cd3f-11e7-82aa-7db800442fde.png)

**styl：**

![default](https://user-images.githubusercontent.com/22829291/32988549-92d35718-cd41-11e7-97c4-d16c726bae99.png)

**I hope `Sublime-HTMLPrettify` can beautify the` styl` file.
If not, I want to disable `Sublime-HTMLPrettify` beautification of styl
I tried the following method, nor does it work：**

```
"disallowed_file_patterns": ["styl","stylus"]
```

```
/* beautify ignore:start */
This is some styl code
/* beautify ignore:end */
```

**Comment by Timm-Lee** [comment]
I have some demand as @roy-lau. Can we temporarily close the css beautify function for stylus part in ".vue" file?

**Comment by roy-lau** [comment]
Please tell me first how to close the `stylus` `.vue`. However, I still want to be able to format `stylus` in `.vue`

**Comment by Timm-Lee** [comment]
@roy-lau So far, I switched to use VS Code with Vetur + Prettier. Waiting for better Sublime.

**Comment by iamdubx** [comment]
Also have this issue.

**Comment by roy-lau** [comment]
@Timm-Lee  I'm using it   Sublime Text3

**Comment by mesqueeb** [comment]
I also want to be able to prettify Stylus CSS in vue files. How do I do this in Sublime 3?

**Comment by rockyx128** [comment]
我也是

**Comment by victorporof** [comment]
Please file this at https://github.com/beautify-web/js-beautify
