### ISSUE TITLE
Prettify breaking stylelint-disable-line comments.

### ISSUE THREAD

**Issue by IcarusTalon** [victorporof/Sublime-HTMLPrettify#510]
If I have a line of CSS with a comment to ignore a stylelint rule, like this:

display:block!important; /* stylelint-disable-line declaration-no-important */

When I run Prettify, it replaces the space before the comment with a newline, which ends up looking like this:

display:block!important;
/* stylelint-disable-line declaration-no-important */

Which basically removes my ablility to make line level exceptions to stylelint. :(

I would imagine that a Prettify should ignore comments in general anyway?

**Comment by victorporof** [comment]
Please file this issue at https://github.com/beautify-web/js-beautify
