### ISSUE TITLE
space after 'async'

### ISSUE THREAD

**Issue by astanciu** [victorporof/Sublime-HTMLPrettify#513]
before:

```Javascript
const obj = {
  mything: async (param) => {}
}
```

After:

```Javascript
const obj = {
  mything: async(param) => {}
}
```

This was fixed in jsbeautify version 1.7.4 ( https://github.com/beautify-web/js-beautify/blob/master/CHANGELOG.md )

Can we upgrade the jsbeautify version? Or is there another workaround?

**Comment by gamegee** [comment]
The package control currently don't match the github version.
Any news @victorporof ?

**Comment by victorporof** [comment]
Dupe of https://github.com/victorporof/Sublime-HTMLPrettify/issues/492
Will update soon!
