### ISSUE TITLE
Cant Handle Babel/JSX

### ISSUE THREAD

**Issue by datner** [victorporof/Sublime-HTMLPrettify#517]
Tried to beautify some JSX and got some wierd gibrish as such:
![beautify wtf](https://user-images.githubusercontent.com/22598347/34028008-0c217d1c-e169-11e7-9f50-4901feb0bf2c.png)

**Comment by wggley** [comment]
+1

**Comment by victorporof** [comment]
Yup, it can't. I'm not sure if it should (I wish it would!), but in any case, this decision should be made here: https://github.com/beautify-web/js-beautify Please file an issue there.
