### ISSUE TITLE
On every save in css file it inserts blanks lines between rules

### ISSUE THREAD

**Issue by sanaalazmeh** [victorporof/Sublime-HTMLPrettify#521]
On every save in css file it inserts blanks lines between rules
in the end, all the file is filled blank lines (100s)
Please fix.
Thanks.

**Comment by minikN** [comment]
+1

**Comment by venhryk** [comment]
+1

**Comment by victorporof** [comment]
Dupe of https://github.com/victorporof/Sublime-HTMLPrettify/issues/492
