### ISSUE TITLE
deletes the code

### ISSUE THREAD

**Issue by ssnakee2** [victorporof/Sublime-HTMLPrettify#523]
i run program and it deletes the html.

no further information required.
simply deletes all the code.
blank page.

**Comment by victorporof** [comment]
Can you take a look at the existing issues filed for this plugin? If you can't find something that matches your issues, please reopen with more details if possible.

Obviously if there was such a nuclear issue with the plugin, everyone would have noticed it by now. Some minimal steps to reproduce would be useful.

**Comment by ssnakee2** [comment]
I have edited the comment

**Comment by ssnakee2** [comment]
Sorry that I was so rude and immature in the original post.
