### ISSUE TITLE
How to use only HTML prettify?

### ISSUE THREAD

**Issue by hackuun** [victorporof/Sublime-HTMLPrettify#524]
Is there an option to use only HTML prettify? I don't want to fix my JS or CSS woth this plugin, it doing it wrong.

**Comment by victorporof** [comment]
No :)

**Comment by alo0oz** [comment]
Yes. I was having strange problem while prettifying "css" documents with this plugin, it was adding an extra "new line" above every comment at every turn. most of the plugins default settings are not editable. But i was able to edit this plugins default settings & commented out the css portion. and now it's not prettifying css files. I'm on linux i dont know about other OSs
