### ISSUE TITLE
For some reason adds a space (blank) before the quote!

### ISSUE THREAD

**Issue by dimsis** [victorporof/Sublime-HTMLPrettify#526]
For example, check out the following HTML after prettifying it:
```
 <div class="col-md-6 text-center ">
                        <ul class="list-inline list-unstyled ">
                            <li class="list-inline-item "><a href="# ">Contact Us</a></li>
```

Can you see the SPACE before all ending double quotes?

**Comment by sahilg14** [comment]
I am having the same problem. It also did that to id, causing js to fail.

**Comment by victorporof** [comment]
Dupe of https://github.com/victorporof/Sublime-HTMLPrettify/issues/492
Updating now.
