### ISSUE TITLE
Node.js was not found when it is there

### ISSUE THREAD

**Issue by AndreasBackx** [victorporof/Sublime-HTMLPrettify#53]
I have set my node path to:

<pre><code>{
  // Simply using `node` without specifying a path sometimes doesn't work :(
  // https://github.com/victorporof/Sublime-HTMLPrettify#oh-noez-command-not-found
  // http://nodejs.org/#download
  "node_path": "C:/Program Files/nodejs/node.exe"
}</code></pre>

I'm using the same path for SublimeLinter, HTMLPrettify is still giving me an error when using CTR+SHIFT+H.

**Comment by andersoyvind** [comment]
Happened to me, as well, and the copy/paste from terminal had a space "prefix". All that is needed for it to fail. "linux": " /home/anders/.nvm/versions/node/v4.0.0/bin/node"
----------------^

Check for spaces, first!

**Comment by mrbbp** [comment]
same error, but can't modify the "Nodejs.sublime-settings" and i've no folder in the packages folder in application Support on osx 10.11.2...

**Comment by vlrprbttst** [comment]
all of a sudden, out of the blue, i got the same problem. used to work before yesterday :/

`which node: /usr/local/bin/node``

and my plugin settings:
```
{
  // Simply using `node` without specifying a path sometimes doesn't work :(
  // https://github.com/victorporof/Sublime-HTMLPrettify#oh-noez-command-not-found
  // http://nodejs.org/#download
  "node_path": {
    "osx": "/usr/local/bin/node"
  },

  // Automatically format when a file is saved.
  "format_on_save": false,

  // Only format the selection if there's one available.
  "format_selection_only": true,

  // Log the settings passed to the prettifier from `.jsbeautifyrc`.
  "print_diagnostics": true
}
```

**Comment by skywinder** [comment]
Same problem and same settings as @victorporof :cry:

**Comment by victorporof** [comment]
Hmm, how are y'all opening Sublime? I've seen such errors sometimes when opening directly from the shell via a `subl` link to the sublime executable from my /usr/local/bin. Looks like in those cases Sublime simply doesn't care about environment vars and paths anymore, but I'm not entirely sure what happens.

**Comment by vlrprbttst** [comment]
mine magically works again. I didn't do anything though :)

**Comment by anyotherway** [comment]
•	2016-02-01 magically what?
Dumping this app. Developer has elected to move over to Atom which-also-then-sucks, Gossip? 
•	Sublime is falling apart
no longer auto saves - no longer reopens files open on close - no longer formats HTML correctly
MUST MANUAL CORRECT EVERY LINE 
•	DEAD PROJECT on mac... assange-snowdon closet-love toy now? grief!

**Comment by vlrprbttst** [comment]
@anyotherway i switched to atom in fact ;) which doesn't suck at all in my opinion

**Comment by anyotherway** [comment]
time for a revisit, thanks

**Comment by mainpart** [comment]
stopped working

    Using node.js path on 'windows': h:/Program Files/nodejs/node.exe
    Unexpected error(<class 'OSError'>): [WinError 6] Неверный дескриптор

path is totally correct

**Comment by wangyongf** [comment]
Restart and everything is OK! Just for my case

**Comment by victorazevedo** [comment]
In windows I have unistalled and reinstalled the plugin ' HTML-CSS-JS Prettify ' and CTRL+SHIFT+H is now working. Hope it helps

**Comment by bhanurao** [comment]
Here is one which worked for me
  "node_path": {
    "windows": "C:/Program Files/nodejs/node",
    "linux": "/usr/bin/nodejs",
    "osx": "/usr/local/bin/node"
  },

**Comment by ztwei** [comment]
run into the same problem...
osx 10.12.1
sublime build 3126
which node => /usr/local/bin/node

package not working without any error displayed, any suggestion?

**Comment by taooco** [comment]
@yashangqingsong's  solution is right for Windows Version. the key point is point out the file path which need to modify. the path: C:\Program Files (x86)\Sublime Text\Data\Packages\HTML-CSS-JS Prettify\HTMLPrettify.sublime-settings

**Comment by CharlotteBao** [comment]
I resolved by step:
1. uninstall nodejs
2. remove htmlprettify
3. reinstall nodejs
4.reinstall htmlprettify
then, i dont know why, but it worked. 

"node_path": {
    "windows": "D:/Program Files/nodejs/node.exe",
    "linux": "/usr/bin/nodejs",
    "osx": "/usr/local/bin/node"
  }

**Comment by Firex** [comment]
In case somebody keep getting this message (for windows):

1. Get error
2. Open console 'Ctrl + `'
3. Copy Command '**WHEATEVER_IS_HERE**' returned non-zero exit status 1
error: You won't be able to use this plugin without specifying the path to node.js.
4. Now try to execute it in 'cmd' You will get a better explanation on what going on.

In my case, the 'run.js' of HTML prettify was missing - removing and installing the plugin again worked as a charm.

**Comment by Willemstijn** [comment]
I use Windows 7 x64 and Sublime Text 3 b3126 with the latest version of Prettify.
Also had the same problem problem and solved it by changing the default windows path slashes from:

**C:\some\path\to\nodejs\node.exe**

to:

**C:/some/path/to/nodejs/node.exe**

 and now it works!!!

Just my 2 cents...

**Comment by darrenfantasy** [comment]
restart sublime,it works.

**Comment by webant** [comment]
The plugin works only in files opened in Group 1 and Group 2 (on sideboards without Folders).
Everything is fine here, but ...
The plugin gives errors when formatting a file opened in a FOLDER (on sideboards with Folders).
How to fix it?

**Comment by TheCrookedMan** [comment]
@generic-user I use this method, it works.

**Comment by ahmadalfy** [comment]
In my condition this error happened because I was using nvm. Node was accessible from the terminal yet sublime couldn't see it. I set the URL manually in the settings by typing the following in the terminal:

    which node

And copied the output and added to `node_path` in the settings:

    "node_path": whatever-the-url-you-get-from-the-previous-command,

Then you have to shut down sublime completely. Start it again then it will work

**Comment by LeonardoGentile** [comment]
This is still not working for me.
I'm in the exact condition of @ahmadalfy and I did the same exact steps. 
But that didn't work for me (on mac os, ST3)

**Comment by henrik8000** [comment]
"osx": "/usr/local/Cellar/node/8.5.0/bin/node"

**Comment by AnmolTomer** [comment]
2020 and it is still not working.

**Comment by Fulguritude** [comment]
This seems to be an issue from Sublime-Text itself: I have made the following post on their forums. https://forum.sublimetext.com/t/bug-sublime-text-cant-find-nodejs-on-pop-os-ubuntu-20-04/55553
