### ISSUE TITLE
“space_after_anon_function” doesn't work in html

### ISSUE THREAD

**Issue by dawufenfen** [victorporof/Sublime-HTMLPrettify#530]
I changed "space_after_anon_function" to true,then I used Prettify in JS,it worked.But when I used in HTML,the function in <script> was still "function()".
It bothers me because I use Vue and it will throws an error that says  “Missing space before function parentheses” if so.

**Comment by victorporof** [comment]
I'd love for this to be supported. Unfortunately, the decision to support vue lies with the underlying prettifier library author. File a request here: https://github.com/beautify-web/js-beautify
