### ISSUE TITLE
How to prettify selected HTML and JS in php file?

### ISSUE THREAD

**Issue by rizkyarlin** [victorporof/Sublime-HTMLPrettify#532]

**Comment by djmtype** [comment]
Try adding the php file extension to HTMLPrettify's Plugin Options user settings file:
(Although, there might be some good reason it wasn't included in the first place.)
```
{
	"global_file_rules":
    {
    	 "html":
        {
            "allowed_file_extensions": ["htm", "html", "xhtml", "shtml", "xml", "svg", "php"]
        }
    }
}
```

**Comment by victorporof** [comment]
@djmtype's answer is the right one! Thanks for replying!
