### ISSUE TITLE
Don't run if .jsbeautifyrc is not present

### ISSUE THREAD

**Issue by amenadiel** [victorporof/Sublime-HTMLPrettify#539]
I get that 

> The plugin looks for a .jsbeautifyrc file in the same directory as the
> source file you're prettifying (or any directory above if it doesn't exist,
> or in your home folder if everything else fails) and uses those options
> along the default ones.

However, I use other formatter plugins in some of my projects (e.g. [sublime-vue-formatter](https://github.com/luozhihua/sublime-vue-formatter)) I'm trying to find the proper way to avoid running Sublime-HTMLPrettify when the file `.jsbeautifyrc` is not present. It seems there's no such option. Of course, my intention is to format on save (on both plugins) so both plugins would conflict with each other if given different rules.

For the moment, I'm trying two workarounds. 

1. define the default `.jsbeautifyrc` (in sublime's `Packages/User` folder) to  allow no file extension:

```json
{
    "all":
    {
        "allowed_file_extensions": []
    },

    "html":
    {
        "allowed_file_extensions": []
    },

    "css":
    {
        "allowed_file_extensions": []
    },

    "js":
    {
        "allowed_file_extensions": []
    },

    "json":
    {
        "allowed_file_extensions": []
    },

    "custom":
    {
      "allowed_file_extensions": []
    }
}
```

2. Do the same on `Packages/User/HTMLPrettify.sublime-settings` 

```json
    "global_file_rules":
    {
        "html":
        {
            "allowed_file_extensions": [],
            "allowed_file_syntaxes": ["html", "xml"],
            "disallowed_file_patterns": []
        },
        "css":
        {
            "allowed_file_extensions": [],
            "allowed_file_syntaxes": ["css", "sass", "less"],
            "disallowed_file_patterns": []
        },
        "js":
        {
            "allowed_file_extensions": [],
            "allowed_file_syntaxes": ["javascript", "ecma"],
        },
        "json":
        {
            "allowed_file_extensions": [],
            "allowed_file_syntaxes": ["json"],
        }
    },

```

What would be the correct approach? My concern is also that these user options doesn't get merged with the default options on `Packages/HTML-CSS-JS Prettify` because if I edit those files, they will get overwritten on the next release.

As a sidenote, esformatter allows to define a property on a given `.esformatterrc` 
https://github.com/millermedeiros/esformatter/blob/master/doc/config.md#root

> Settings from multiple files will be merged until it finds a config file that contains the property "root": true;

Such a feature  would allow to define no allowed file extensions for a given project, without touching the default .jsbeautify

**Comment by victorporof** [comment]
I don’t think either one of your workarounds would work unfortunately. Even more, “allowed_file_extensions” shouldn’t do anything in a jsbeautifyrc file afaik.

I believe this issue would sove your use case: https://github.com/victorporof/Sublime-HTMLPrettify/issues/267 Duping to that, but feel free to reopen if not.

Pull requests welcome!

**Comment by amenadiel** [comment]
Yeah I've noticed it doesn't have any effect. The only way to deal with my desired behavior is to add a certain project path to `disallowed_file_patterns`
