### ISSUE TITLE
Adds extra spaces

### ISSUE THREAD

**Issue by djmtype** [victorporof/Sublime-HTMLPrettify#541]
Prettifying CSS adds a single space around every hyphen, symbol characterand between a number and its unit of measure.

**Comment by djmtype** [comment]
I think the problem is I added php to the list of html file extensions, otherwise it won't prettify the html inside php files. Why this would affect the formatting of css files in an unpredictable way – I have no idea. 

```
"global_file_rules":
  {
    "html":
      {
        "allowed_file_extensions": ["htm", "html", "xhtml", "shtml", "xml", "svg", "php"],
        "allowed_file_syntaxes": ["html", "xml"],
        "disallowed_file_patterns": []
      }
  }
```

**Comment by djmtype** [comment]
The only work around I found is to dump all rules inside the HTMLPrettify.sublimesettings doc—which isn't ideal since it feels redundant.

I should be allowed to extend html like this: 

```
"global_file_rules": {
  "html": {
      "allowed_file_extensions": ["htm", "html", "xhtml", "shtml", "xml", "svg", "php"]
    }
}
```

While not having to include the kitchen sink again, like this: 

```
{
  "global_file_rules":
  {
    "html":
    {
      "allowed_file_extensions": ["htm", "html", "xhtml", "shtml", "xml", "svg", "php"]
    },
    "css":
    {
      "allowed_file_extensions": ["css", "scss", "sass", "less"]
    },
    "js":
    {
      "allowed_file_extensions": ["js"]
    },
    "json":
    {
      "allowed_file_extensions": ["json", "jshintrc", "jsbeautifyrc"],
    }
  }
}
```

**Comment by victorporof** [comment]
Ah, I see what’s going on here. Preferences aren’t extended, but overridden by the user config.

AFAIK this is the default sublime behaviour, but I concur that it’s confusing.

**Comment by victorporof** [comment]
There’s a big comment in the settings file that points this out: https://github.com/victorporof/Sublime-HTMLPrettify/blob/master/HTMLPrettify.sublime-settings#L34

Not sure what else to do here except actually implement merged settings.
