### ISSUE TITLE
【疑难求助】html-css-js pretty 插件格式化html文档后script 标签内容全部连成一行代码了 

### ISSUE THREAD

**Issue by 429463267** [victorporof/Sublime-HTMLPrettify#545]
## 【疑难求助】html-css-js pretty 插件格式化html文档后script 标签内容全部连成一行代码了 ##

html-pretty 插件格式化后的代码如下图：

![](http://my-public-pic.oss-cn-shenzhen.aliyuncs.com/18-4-14/56009462.jpg)

理论上讲，script 标签内容应该按照java 语法格式书写，一个分号换一行，以下是正确格式：

![](http://my-public-pic.oss-cn-shenzhen.aliyuncs.com/18-4-14/50837306.jpg)

# 附源代码

```html
<!DOCTYPE HTML>
<html>

<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <title>单选按钮</title>
  <style type="text/css">
  #all div {
    display: none;
  }
	</style>
	<script type="text/javaScript">
  function show(obj){ var oDiv = document.getElementById("result"+obj.value); var aDiv = document.getElementById("all").getElementsByTagName("div"); for(var i=0; i
  <aDiv.length; i++){ aDiv[i].style.display="none" ; } oDiv.style.display="block" ; } </script>

</head>
```

**Comment by huaiguang** [comment]
#Problem
- 在格式化 .vue 文件时，template， script,  style 中间也没有空行, 希望可以提供选项， 像 head, body那样单独成块。
- 示例 
![_20180427103640](https://user-images.githubusercontent.com/13193324/39341705-fdeee4da-4a06-11e8-8176-511f22eb9d96.png)
![_20180427103731](https://user-images.githubusercontent.com/13193324/39341706-fe3968ac-4a06-11e8-949a-c7985ab034f3.png)

**Comment by snipertulip** [comment]
@huaiguang 这个应该可以配置吧

**Comment by huaiguang** [comment]
@snipertulip 我找了一遍，还是没有找到，能告诉我在哪里设置吗？ 目前 .vue 是使用html设置来格式化的，而默认的只有head和body是能够当成块空一行，这个问题应该和上面是一样的。

**Comment by snipertulip** [comment]
@huaiguang 我win10的系统都可以格式化呢，你的什么系统。

**Comment by victorporof** [comment]
Please file this issue at https://github.com/beautify-web/js-beautify

**Comment by 9776887181** [comment]
同问
