### ISSUE TITLE
在html的unformatted中， ‘pre’多余了一个。

### ISSUE THREAD

**Issue by huaiguang** [victorporof/Sublime-HTMLPrettify#548]
# problem
 -  在 prettify preferences 中html的"unformatted"，  pre重复了一次。
![_20180427104105](https://user-images.githubusercontent.com/13193324/39341812-7c6ff04c-4a07-11e8-9ce8-244d12485917.png)

**Comment by victorporof** [comment]
Eh, not a big deal :)
