### ISSUE TITLE
无法使用HTML-CSS-JS Prettify插件用于格式化html

### ISSUE THREAD

**Issue by ChaseCode** [victorporof/Sublime-HTMLPrettify#560]
我已经安装好了node.js环境并且配置了环境变量等。HTML-CSS-JS Prettify插件我在sublime也设置node.js的路径，为什么还是用不了呢？
C:\develop\node-v10.1.0-win-x64>npm -v
5.6.0

C:\develop\node-v10.1.0-win-x64>node -v
v10.1.0

**Comment by victorporof** [comment]
Dupe of https://github.com/victorporof/Sublime-HTMLPrettify/issues/553
