### ISSUE TITLE
How do I preserve line breaks with sass comments

### ISSUE THREAD

**Issue by djmtype** [victorporof/Sublime-HTMLPrettify#569]
On .scss files, I prefer my comma separated items on one line. 

For example, I prefer this: 
```
h1, h2, h3 {
  …
}
```

So, inside .jsbeautifyrc, I specify: 

```
"css": {
  "selector_separator_newline": false
 }
```

However, then my sass comments (`// my comment`) inside .scss files, will be placed inline with the previous rule, but I want them kept on a separate line.

Example as intended: 
```
.card {
  background: white;
  // color: black;
}
```

Example after Prettify: 
```
.card {
  background: white; // color: black;
}
```

How can this be accomplished?

**Comment by victorporof** [comment]
Is there any possibility of accomplishing this with https://github.com/beautify-web/js-beautify ?

**Comment by djmtype** [comment]
I already looked at their docs. I couldn't get it to work in my favor. In most places—not all—it ignores to put sass-flavored comments on their own line whether `selector_separator_newline` is set to true or false. And I don't see a reason or pattern why it would do that. I use the same kind of single-line comments in JS, and Prettify respects those.

**Comment by djmtype** [comment]
BTW, If I use regular css comments (`/* comment */`), there's no issue—Prettify respects them.

**Comment by victorporof** [comment]
I suggest filing this feature request here: https://github.com/beautify-web/js-beautify 

This plugin uses that library.
