### ISSUE TITLE
Node JS runtime error (node:6967)

### ISSUE THREAD

**Issue by wheatbrad** [victorporof/Sublime-HTMLPrettify#574]
Cryptic Node JS runtime error when prettifying small HTML file.

`Node.js encountered a runtime error: (node:6967)`

Sublime Text -v 3.1.1
Node -v 10.1.0

Oddly enough, after encountering the runtime error, HTMLPrettify will prettify the markup and print to the Sublime Text console.

**Comment by victorporof** [comment]
Dupe of https://github.com/victorporof/Sublime-HTMLPrettify/issues/576
