### ISSUE TITLE
I get some error when I'm try use prettify

### ISSUE THREAD

**Issue by Prestapro** [victorporof/Sublime-HTMLPrettify#576]
Hello,
It' great plugin, but today I get this bug
http://prntscr.com/jn3rz3
And I don't know what to do.
Thank's

**Comment by victorporof** [comment]
What's the output in sublime's console?

**Comment by pchhetri** [comment]
On a Mac, upgrading to Node v10.2.1 resolves the issue.

---

If you are on an older build of Node v10, you can upgrade the the `fs-extra` npm package this plugin uses to version `6.0.1`. 

On a mac, go to the following directory: `~/Library/Application Support/Sublime Text 3/Packages/HTML-CSS-JS Prettify/build/js-transpiled`. In the package.json file change `"fs-extra": "3.0.1",` to `"fs-extra": "6.0.1",` and then run `npm install` in that directory via terminal.

---
@victorporof can you update the following npm packages used in this plugin to the latest versions?

```
"fs-extra": "3.0.1",
"js-beautify": "1.6.14",
```

The update to js-beautify would resolve this issue https://github.com/victorporof/Sublime-HTMLPrettify/issues/451  which has been addressed in js-beautify https://github.com/beautify-web/js-beautify/issues/1219

**Comment by leafiy** [comment]
same issue on win10 + nodejs 10.4
but its ok after I downgrade nodejs to v8.11.2
dont know why

**Comment by victorporof** [comment]
Should be fixed now! Update to 2.2.0 https://github.com/victorporof/Sublime-HTMLPrettify/releases

If not, please send a feature request to https://github.com/beautify-web/js-beautify/issues
