### ISSUE TITLE
How can I control empty space about annotation?

### ISSUE THREAD

**Issue by MOONLIGHTV** [victorporof/Sublime-HTMLPrettify#578]
As you see, how can I control empty space about annotation?
I tried to added rule to jsbeautifyrc but doesn't work:

"css":
    {
        // You can add other .jsbeautifyrc rules in this section too.
        "max_preserve_newlines": 0,
    } 
![pro-1](https://user-images.githubusercontent.com/14039419/40886628-3b245572-676e-11e8-9fd2-5ce5c33c6b5e.gif)

**Comment by victorporof** [comment]
This should be fixed by https://github.com/victorporof/Sublime-HTMLPrettify/issues/492 ...which I should really get to one of these days.
