### ISSUE TITLE
Runtime error encountered

### ISSUE THREAD

**Issue by tekHudson** [victorporof/Sublime-HTMLPrettify#579]
Runtime error encountered. Attached is the output in my logs
[html pretiffy error.txt](https://github.com/victorporof/Sublime-HTMLPrettify/files/2086436/html.pretiffy.error.txt)

The output in the console is correctly formatted and works as far as I can tell.

It's just not putting it back in the editor.

**Comment by tekHudson** [comment]
The output in the console is correctly formatted and works as far as I can tell.

**Comment by victorporof** [comment]
This error should be fixed by updating to the latest version of this plugin. See https://github.com/victorporof/Sublime-HTMLPrettify/issues/553

**Comment by tekHudson** [comment]
I got this error using package manager. Does that not pull latest?

**Comment by victorporof** [comment]
@tekHudson It should, but I don't know why it didn't update in your case.
