### ISSUE TITLE
How can I add space left and right to css/scss operator?

### ISSUE THREAD

**Issue by MOONLIGHTV** [victorporof/Sublime-HTMLPrettify#581]
How can I add space left and right to css/scss operator?
Operator like "+","-","*","/" doesn't work if has no space in calc();
![default](https://user-images.githubusercontent.com/14039419/41450428-42fc9446-709a-11e8-9518-b516f8f6c1f2.png)

Need let it from before to after

**Comment by victorporof** [comment]
Please file this question at https://github.com/beautify-web/js-beautify Thanks!
