### ISSUE TITLE
A runtime error was encountered in the prettifier.

### ISSUE THREAD

**Issue by vishnusinghchauhan** [victorporof/Sublime-HTMLPrettify#584]
hello,
when i save my file i am getting below  message . how can i solve this.
A runtime error was encountered in the prettifier. See the console output for more information. Do you wish to file a bug?

**Comment by victorporof** [comment]
What is the output in sublime’s console?

**Comment by victorporof** [comment]
Should be fixed already by the previous release! Update to 2.2.0 https://github.com/victorporof/Sublime-HTMLPrettify/releases to make sure.

**Comment by victorporof** [comment]
Of course, please reopen if not :)
