### ISSUE TITLE
Preserve or Ignore do not work with SCSS

### ISSUE THREAD

**Issue by djmtype** [victorporof/Sublime-HTMLPrettify#586]
I've tried wrapping certain properties with`/* beautify preserve:start */ … /* beautify preserve:end */` and `/* beautify ignore:start */ … /* beautify ignore:end */`. But, it doesn't seem to work with scss. 

I don't want to format certain areas of my css that use `grid-template-areas` so they're easier for me to read. Otherwise, all of the line names get placed on a single line when they're ran through Sublime-HTMLPrettify. 

Is there a way around this?

**Comment by bitwiseman** [comment]
https://github.com/beautify-web/js-beautify/issues/813

**Comment by victorporof** [comment]
Should be fixed now! Update to 2.2.0 https://github.com/victorporof/Sublime-HTMLPrettify/releases

If not, please send a feature request to https://github.com/beautify-web/js-beautify/issues
