### ISSUE TITLE
Linux using NVM - Node.js not found, should look at environment variable.

### ISSUE THREAD

**Issue by benwinding** [victorporof/Sublime-HTMLPrettify#590]
This package immediately broke on install, the reason was it couldn't find the node binary. 

I suspect many people using this package would be developers, most likely using NVM (node version manager). So this error would happen to a lot of people.

**Problem**
If you're using NVM, you need to specify the specific version of node that you're using, for example:

    "node_path":
    {
        "linux": "/home/ben/.nvm/versions/node/v8.9.4/bin/node"
    },

However, when you're using NVM it's common to remove and install lot's of node versions.

**Solution**
The current node version is always referenced in the variable $NVM_BIN.

    $ echo  $NVM_BIN
    /home/ben/.nvm/versions/node/v8.9.4/bin

Is it possible to use this environment variable in the settings for this package? something like the following:

    "node_path":
    {
        "linux": " $NVM_BIN/node"
    },

If this is not possible, then it's probably best that the script should just TRY and use this environment variable if the 'node_path' variable doesn't exist on the file system.

**Comment by victorporof** [comment]
This was the initial way the plugin worked many moons ago.

Unfortunately, the horrendous way sublime is handling environment variables (depending on how the app is opened) makes this even more fragile than just asking the user for a path.

Would love to be proven wrong.

**Comment by Pavanyogi121** [comment]
if we specify the node_path like "linux": "/home/pavan/.nvm/versions/node/v16.16.0/bin/node", then it is working. but if we specify the path like "linux": " $NVM_BIN/node" then it is not working. May be some condition can be added in the code section to check the node with nvm.

```py
# env_utils.py
def get_node_path():
    """Gets the node.js path specified in this plugin's settings file"""
    node = get_pref("node_path").get(PLATFORM)
    return expanduser(node)
```
