### ISSUE TITLE
I've installed the node.js 10 and set the path of node.js correctly but it still reminded me that couldn't find the node.js in the default path.

### ISSUE THREAD

**Issue by kaikai123123** [victorporof/Sublime-HTMLPrettify#591]
I have tried many ways to solve this problem but did't succeed. I'm using the windows 10 system subline text3. I've tried  installed node.js 8 but it did not work.

**Comment by victorporof** [comment]
Duping to https://github.com/victorporof/Sublime-HTMLPrettify/issues/531
