### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by brijesh5470** [victorporof/Sublime-HTMLPrettify#592]
not working

**Comment by coreystinson2** [comment]
Consider providing more information to help maintainers provide you with a solution.

**Comment by devleaks** [comment]
Plain vanilla install on Sublime Text 3, and it was not working either. I found [this](https://blog.damirmiladinov.com/vuejs/beautify-vuejs.html) useful. The package was simply not processing vue files (!). It now works as expected. P. As mentionned, viewing the messages on the console was helpful.

**Comment by victorporof** [comment]
All you had to do was add vue as an enabled file extension, as per readme.

Update to 2.2.0 https://github.com/victorporof/Sublime-HTMLPrettify/releases This plugin now supports vue files by default!
