### ISSUE TITLE
Feature Request: unindent chained methods

### ISSUE THREAD

**Issue by gaby64** [victorporof/Sublime-HTMLPrettify#596]
already implemented here https://github.com/beautify-web/js-beautify/commit/ed61dc1156f1476df697f39571a465e1141c1df7

**Comment by victorporof** [comment]
I really need to update beautify... :)

**Comment by victorporof** [comment]
Should be fixed now! Update to 2.2.0 https://github.com/victorporof/Sublime-HTMLPrettify/releases

If not, please send a feature request to https://github.com/beautify-web/js-beautify/issues
