### ISSUE TITLE
collapse-preserve-inline does not work in javascript

### ISSUE THREAD

**Issue by tifDev** [victorporof/Sublime-HTMLPrettify#597]
I want to put braces on own line (Allman / ANSI style) but its not working, it does the same as the default style....
I want functions like this:

```
function foo() 
{
    var x = 1;

}
```

**Comment by victorporof** [comment]
Should be fixed now! Update to 2.2.0 https://github.com/victorporof/Sublime-HTMLPrettify/releases

If not, please send a feature request to https://github.com/beautify-web/js-beautify/issues
