### ISSUE TITLE
HTML formatiing results are strange

### ISSUE THREAD

**Issue by nyschoi** [victorporof/Sublime-HTMLPrettify#599]
I use sublime 3.1.1 and install prettify today. I didn't change anything about settings.

Why I execute HTMLprettier, reformatted results are strange.

[https://github.com/nyschoi/kakaoClone/blob/master/screenshot/2018-09-03%205.19.06.png](url)

Sorry. I can't find how can I attach my screenshot in GitHub.

instead, I left my GitHub URL
https://github.com/nyschoi/kakaoClone/tree/master/screenshot
and my screenshot file name is : 2018-09-03 5.19.06.png

what should I do?

**Comment by victorporof** [comment]
Please file this issue at https://github.com/beautify-web/js-beautify
