### ISSUE TITLE
[Question] How not to format templating tags?

### ISSUE THREAD

**Issue by kud** [victorporof/Sublime-HTMLPrettify#602]
I've got something like this with this plugin:

```
{% extends 'v2/users/account/base.html' %}

{% load static form_tags %}

{% block title %}Test{{ block.super }}{% endblock %}

{% block content %}
{% endblock content %}
```

It results as:

```
{% extends 'v2/users/account/base.html' %} {% load static form_tags %} {% block title %}Test{{ block.super }}{% endblock %} {% block content %} {% endblock content %}
```

However, when I do it on https://beautifier.io/, I don't have this result.

And I'd like to have the same result that I've got on beautifier.

I don't find the setting which compresses the templating tags, do you know which one is?

Thank you.

**Comment by victorporof** [comment]
Should be fixed now! Update to 2.2.0 https://github.com/victorporof/Sublime-HTMLPrettify/releases

Please reopen if not.

**Comment by kud** [comment]
Thank you @victorporof! I'll try this. :)

**Comment by victorporof** [comment]
Also, be sure to post sublime's output if it still happens.
