### ISSUE TITLE
[CSS] Add an extra space above every comment in every turn

### ISSUE THREAD

**Issue by alo0oz** [victorporof/Sublime-HTMLPrettify#603]
Please correct this.
This is very annoying.
I had to comment out the css portion of the default settings to stop prettifying css files.
And now i have to use csscomb for prettifying css documents, an extra overhead.

**Comment by zengnificant** [comment]
add "preserve_newlines": false into "css": {...} in .jsbeautifyrc            #492

**Comment by victorporof** [comment]
Should be fixed now! Update to 2.2.0 https://github.com/victorporof/Sublime-HTMLPrettify/releases
