### ISSUE TITLE
Couldn't use prettifier with SublimeText 3.1.3

### ISSUE THREAD

**Issue by nganmcb** [victorporof/Sublime-HTMLPrettify#609]
SublimeText v3.1.1
HTML-CSS-JS Prettify v2.2.2
Couldn't use the feature _pretify code_ as the error:
"A runtime error was encountered in the prettifier. See the console output for more information"

Tried serveral time remove/reinstall but it doesn't help

https://www.screencast.com/t/XB6Gw01Svmc

**Comment by victorporof** [comment]
Likely a dupe of https://github.com/victorporof/Sublime-HTMLPrettify/issues/610
