### ISSUE TITLE
Runtime error

### ISSUE THREAD

**Issue by igor-ws** [victorporof/Sublime-HTMLPrettify#610]
Hello,
runtime error keeps popping up since this morning. Clean install didn't help.

Console output:

DPI mode: per-monitor v2
startup, version: 3176 windows x64 channel: stable
executable: /C/Program Files/Sublime Text 3/sublime_text.exe
working dir: /C/Program Files/Sublime Text 3
packages path: /C/Users/username/AppData/Roaming/Sublime Text 3/Packages
state path: /C/Users/username/AppData/Roaming/Sublime Text 3/Local
zip path: /C/Program Files/Sublime Text 3/Packages
zip path: /C/Users/username/AppData/Roaming/Sublime Text 3/Installed Packages
ignored_packages: ["Vintage"]
Errors parsing theme:
icon_file_type is missing layer0.opacity, setting to 1.0 for backwards compatibility
pre session restore time: 0.373895
startup time: 0.436895
first paint time: 0.459895
reloading plugin Default.arithmetic
reloading plugin Default.auto_indent_tag
reloading plugin Default.block
reloading plugin Default.colors
reloading plugin Default.comment
reloading plugin Default.convert_color_scheme
reloading plugin Default.convert_syntax
reloading plugin Default.copy_path
reloading plugin Default.delete_word
reloading plugin Default.detect_indentation
reloading plugin Default.duplicate_line
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.indentation
reloading plugin Default.install_package_control
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_context_url
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.profile
reloading plugin Default.quick_panel
reloading plugin Default.rename
reloading plugin Default.run_syntax_tests
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.settings
reloading plugin Default.show_scope_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.swap_line
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.trim_trailing_white_space
reloading plugin Default.ui
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin ShellScript.ShellScript
reloading plugin 0_package_control_loader.00-package_control
reloading plugin 0_package_control_loader.01-pygments
reloading plugin 0_package_control_loader.50-backrefs
reloading plugin 0_package_control_loader.50-dateutil
reloading plugin 0_package_control_loader.50-markupsafe
reloading plugin 0_package_control_loader.50-pymdownx
reloading plugin 0_package_control_loader.50-python-markdown
reloading plugin 0_package_control_loader.50-pyyaml
reloading plugin 0_package_control_loader.51-python-jinja2
reloading plugin 0_package_control_loader.55-jsonschema
reloading plugin 0_package_control_loader.55-mdpopups
reloading plugin A File Icon.A File Icon
reloading plugin AutoFileName.autofilename
reloading plugin AutoFileName.getimageinfo
reloading plugin Bootstrap 3 Autocomplete.bootstrap_3_autocomplete
reloading plugin BracketHighlighter.bh_core
reloading plugin BracketHighlighter.bh_logging
reloading plugin BracketHighlighter.bh_plugin
reloading plugin BracketHighlighter.bh_popup
reloading plugin BracketHighlighter.bh_regions
reloading plugin BracketHighlighter.bh_remove
reloading plugin BracketHighlighter.bh_rules
reloading plugin BracketHighlighter.bh_search
reloading plugin BracketHighlighter.bh_swapping
reloading plugin BracketHighlighter.bh_wrapping
reloading plugin BracketHighlighter.support
reloading plugin Can I Use.useIt
reloading plugin Color Highlighter.color_converter
reloading plugin Color Highlighter.color_highlighter
reloading plugin Color Highlighter.color_hover_listener
reloading plugin Color Highlighter.color_scheme
reloading plugin Color Highlighter.color_scheme_color_highlighter
reloading plugin Color Highlighter.color_searcher
reloading plugin Color Highlighter.color_selection_listener
reloading plugin Color Highlighter.colors
reloading plugin Color Highlighter.content_listener
reloading plugin Color Highlighter.convert_color_command
reloading plugin Color Highlighter.css_colors
reloading plugin Color Highlighter.dummy_event_listener
reloading plugin Color Highlighter.gutter_icons_color_highlighter
reloading plugin Color Highlighter.load_resource
reloading plugin Color Highlighter.main
reloading plugin Color Highlighter.path
reloading plugin Color Highlighter.phantoms_color_highlighter
reloading plugin Color Highlighter.pick_color_command
reloading plugin Color Highlighter.regex_compiler
reloading plugin Color Highlighter.regions
reloading plugin Color Highlighter.set_setting_command
reloading plugin Color Highlighter.settings
reloading plugin Color Highlighter.st_helper
reloading plugin Color Highlighter.topsort
reloading plugin Emmet.emmet-plugin
reloading plugin FindKeyConflicts.find_key_conflicts
reloading plugin Goto Bootstrap.GotoBootstrap
reloading plugin Keymaps.Keymaps
reloading plugin Material Theme.Icons
reloading plugin Material Theme.MT
reloading plugin Package Control.1_reloader
reloading plugin Package Control.2_bootstrap
reloading plugin Package Control.Package Control
reloading plugin ProjectManager.json_file
reloading plugin ProjectManager.project_manager
reloading plugin SideBarEnhancements.SideBar
reloading plugin SideBarEnhancements.SideBarAPI
reloading plugin SideBarEnhancements.SideBarDefaultDisable
reloading plugin SublimeLinter-csslint.linter
reloading plugin SublimeLinter-html-tidy.linter
htmltidy: Defining 'cls.syntax' has been deprecated. Use http://www.sublimelinter.com/en/stable/linter_settings.html#selector
reloading plugin SublimeLinter-jshint.linter
reloading plugin SublimeLinter-xmllint.linter
reloading plugin SublimeLinter.__init__
reloading plugin SublimeLinter.active_linters_view
reloading plugin SublimeLinter.busy_indicator_view
reloading plugin SublimeLinter.goto_commands
reloading plugin SublimeLinter.highlight_view
reloading plugin SublimeLinter.log_handler
reloading plugin SublimeLinter.message_view
reloading plugin SublimeLinter.panel_view
reloading plugin SublimeLinter.status_bar_view
reloading plugin SublimeLinter.sublime_linter
reloading plugin View In Browser.ViewInBrowserCommand
reloading plugin CSScomb.CSScomb
reloading plugin Dictionaries.Dictionaries
reloading plugin HTML-CSS-JS Prettify.HTMLPrettify
reloading plugin Minify.Minify
reloading plugin PlainTasks.APlainTasksCommon
reloading plugin PlainTasks.PlainTasks
reloading plugin PlainTasks.PlainTasksDates
reloading plugin PlainTasks.PlainTasksToHTML
reloading plugin PlainTasks.plist_parser
plugins loaded
SublimeLinter: log_handler.py:74: Logging installed; log level INFO
SublimeLinter: sublime_linter.py:50: debug mode: on
SublimeLinter: sublime_linter.py:51: version: 4.8.0
Node.js encountered a runtime error: Unhandled promise rejection TypeError: Object.entries is not a function
    at extendJsbeautifyConfig (C:\Users\username\AppData\Roaming\Sublime Text 3\Packages\HTML-CSS-JS Prettify\build\js-transpiled\utils\configUtils.js:88:21)
    at _callee2$ (C:\Users\username\AppData\Roaming\Sublime Text 3\Packages\HTML-CSS-JS Prettify\build\js-transpiled\utils\configUtils.js:145:47)
    at tryCatch (C:\Users\username\AppData\Roaming\Sublime Text 3\Packages\HTML-CSS-JS Prettify\build\js-transpiled\node_modules\regenerator-runtime\runtime.js:62:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (C:\Users\username\AppData\Roaming\Sublime Text 3\Packages\HTML-CSS-JS Prettify\build\js-transpiled\node_modules\regenerator-runtime\runtime.js:288:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (C:\Users\username\AppData\Roaming\Sublime Text 3\Packages\HTML-CSS-JS Prettify\build\js-transpiled\node_modules\regenerator-runtime\runtime.js:114:21)
    at asyncGeneratorStep (C:\Users\username\AppData\Roaming\Sublime Text 3\Packages\HTML-CSS-JS Prettify\build\js-transpiled\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\username\AppData\Roaming\Sublime Text 3\Packages\HTML-CSS-JS Prettify\build\js-transpiled\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)

### HTMLPrettify diagnostics begin ###
[HTMLPrettify] Using editor text temp file: True
[HTMLPrettify] Global file rules: {"js": {"allowed_file_syntaxes": ["javascript", "ecma", "react", "babel"], "allowed_file_extensions": ["js", "jsx"], "disallowed_file_patterns": []}, "json": {"allowed_file_syntaxes": ["json"], "allowed_file_extensions": ["json", "babelrc", "eslintrc", "jshintrc", "jsbeautifyrc", "sublime-settings", "sublime-keymap", "sublime-commands", "sublime-menu"], "disallowed_file_patterns": []}, "css": {"allowed_file_syntaxes": ["css", "sass", "less"], "allowed_file_extensions": ["css", "scss", "sass", "less"], "disallowed_file_patterns": []}, "html": {"allowed_file_syntaxes": ["html", "xml", "vue"], "allowed_file_extensions": ["htm", "html", "xhtml", "shtml", "xml", "svg", "vue"], "disallowed_file_patterns": []}}
[HTMLPrettify] Respecting .editorconfig files: True
[HTMLPrettify] Editor file syntax: Packages/CSS/CSS.sublime-syntax
[HTMLPrettify] Editor indent size: ?
[HTMLPrettify] Editor indent with tabs: ?
[HTMLPrettify] Editor text file path: C:\Users\username\AppData\Roaming\Sublime Text 3\Packages\HTML-CSS-JS Prettify\c17bc87a-59b6-48e3-b080-b0397304e1f9
[HTMLPrettify] Editor text file contents: null
[HTMLPrettify] Original file path: D:\myprojects\projectfolder\projectname\css\style.css
[HTMLPrettify] Config extra lookup paths: C:\Users\username\AppData\Roaming\Sublime Text 3\Packages\User,C:\Users\username\AppData\Roaming\Sublime Text 3\Packages\HTML-CSS-JS Prettify
[HTMLPrettify] Computed extra lookup paths for .jsbeautifyrc: ["D:\\myprojects\\projectfolder\\projectname\\css","D:\\myprojects\\projectfolder\\projectname","D:\\myprojects\\projectfolder","D:\\myprojects","D:","C:\\Users\\username","C:\\Users\\username\\AppData\\Roaming\\Sublime Text 3\\Packages\\User","C:\\Users\\username\\AppData\\Roaming\\Sublime Text 3\\Packages\\HTML-CSS-JS Prettify"]
[HTMLPrettify] Attempting to parse file: C:\Users\username\AppData\Roaming\Sublime Text 3\Packages\HTML-CSS-JS Prettify\.jsbeautifyrc.defaults.json
[HTMLPrettify] Attempting to parse file: C:\Users\username\AppData\Roaming\Sublime Text 3\Packages\User\.jsbeautifyrc

Emmet: No need to update PyV8
SublimeLinter: sublime_linter.py:250: Delay buffer 26 for 0.0s
SublimeLinter: linter.py:887: Checking lint mode background vs lint reason on_load
SublimeLinter: #1 linter.py:907: 'csslint' is linting 'style.css'
SublimeLinter: #1 util.py:142: PATH:
    C:\Program Files (x86)\Common Files\Oracle\Java\javapath
    C:\Program Files\ImageMagick-7.0.7-Q16
    C:\ProgramData\Oracle\Java\javapath
    C:\Windows\system32
    C:\Windows
    C:\Windows\System32\Wbem
    C:\Windows\System32\WindowsPowerShell\v1.0\
    C:\Program Files (x86)\GNU\GnuPG\pub
    C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common
    C:\WINDOWS\system32
    C:\WINDOWS
    C:\WINDOWS\System32\Wbem
    C:\WINDOWS\System32\WindowsPowerShell\v1.0\
    C:\Program Files\Microsoft SQL Server\130\Tools\Binn\
    C:\Program Files\dotnet\
    C:\Program Files\Microsoft\Web Platform Installer\
    C:\Program Files\nodejs\
    C:\Program Files (x86)\Brackets\command
    C:\WINDOWS\System32\OpenSSH\
    C:\Program Files (x86)\Microsoft SQL Server\Client SDK\ODBC\130\Tools\Binn\
    C:\Program Files (x86)\Microsoft SQL Server\140\Tools\Binn\
    C:\Program Files (x86)\Microsoft SQL Server\140\DTS\Binn\
    C:\Program Files (x86)\Microsoft SQL Server\140\Tools\Binn\ManagementStudio\
    C:\Program Files (x86)\Skype\Phone\
    C:\Program Files\TortoiseSVN\bin
    C:\Program Files\ImageMagick-7.0.7-Q16
    C:\Users\username\AppData\Local\Programs\Python\Python36-32\Scripts\
    C:\Users\username\AppData\Local\Programs\Python\Python36-32\
    C:\Users\username\AppData\Local\Microsoft\WindowsApps
    C:\Users\username\AppData\Roaming\npm
    C:\Users\username\AppData\Roaming\Tidy_x64
    C:\Users\username\AppData\Roaming\XMLlint

    C:\Users\username\AppData\Local\Programs\Fiddler
SublimeLinter: sublime_linter.py:250: Delay buffer 26 for 0.0s
SublimeLinter: linter.py:887: Checking lint mode background vs lint reason on_save
SublimeLinter: #2 linter.py:907: 'csslint' is linting 'style.css'
SublimeLinter: #1 linter.py:1197: Automatically appending the filename to cmd has been deprecated. Use $file, $temp_file or $file_on_disk instead.
SublimeLinter: #1 linter.py:1263: Running ...

  D:\myprojects\projectfolder\projectname  (working dir)
  > C:\Users\username\AppData\Roaming\npm\csslint.cmd --format=compact --ignore=important,adjoining-classes,universal-selector,box-sizing,order-alphabetical,box-model,unqualified-attributes,font-sizes,regex-selectors c:\users\username\appdata\local\temp\tmporb_wq.css

SublimeLinter: #2 linter.py:1197: Automatically appending the filename to cmd has been deprecated. Use $file, $temp_file or $file_on_disk instead.
SublimeLinter: #2 linter.py:1263: Running ...

  D:\myprojects\projectfolder\projectname  (working dir)
  > C:\Users\username\AppData\Roaming\npm\csslint.cmd --format=compact --ignore=important,adjoining-classes,universal-selector,box-sizing,order-alphabetical,box-model,unqualified-attributes,font-sizes,regex-selectors c:\users\username\appdata\local\temp\tmpcsjcah.css

SublimeLinter: #1 linter.py:955: csslint output:
    c:\users\username\appdata\local\temp\tmporb_wq.css: Lint Free!
SublimeLinter: #1 linter.py:995: csslint: No match for line: 'c:\users\username\appdata\local\temp\tmporb_wq.css: Lint Free!'
SublimeLinter: #2 linter.py:955: csslint output:
    c:\users\username\appdata\local\temp\tmpcsjcah.css: Lint Free!
SublimeLinter: #2 linter.py:995: csslint: No match for line: 'c:\users\username\appdata\local\temp\tmpcsjcah.css: Lint Free!'
SublimeLinter: sublime_linter.py:444: Linting buffer 26 took 0.76s
SublimeLinter: sublime_linter.py:444: Linting buffer 26 took 0.75s
Package Control: Skipping automatic upgrade, last run at 2018-10-01 10:05:56, next run at 2018-10-01 11:05:56 or after

Thanks.

**Comment by victorporof** [comment]
Thanks for the detailed report! Fixing today.

**Comment by victorporof** [comment]
For whoever is affected, the current workaround is updating node to the latest version.

**Comment by nganmcb** [comment]
@victorporof

I upgraded node but it doesn't help. console error (reported in https://github.com/victorporof/Sublime-HTMLPrettify/issues/609) :
_SublimeText v3.1.1
HTML-CSS-JS Prettify v2.2.2_
```
Node.js encountered a runtime error: Unhandled promise rejection TypeError: Object.entries is not a function
    at extendJsbeautifyConfigWithCurrentFileMatchRules (%AppData%\Roaming\Sublime Text 3\Packages\HTML-CSS-JS Prettify\build\js-transpiled\utils\configUtils.js:300:22)
    at Object.finalizeJsbeautifyConfig (%AppData%\Roaming\Sublime Text 3\Packages\HTML-CSS-JS Prettify\build\js-transpiled\utils\configUtils.js:353:34)
    at _callee$ (%AppData%\Roaming\Sublime Text 3\Packages\HTML-CSS-JS Prettify\build\js-transpiled\main.js:77:34)
    at tryCatch (%AppData%\Roaming\Sublime Text 3\Packages\HTML-CSS-JS Prettify\build\js-transpiled\node_modules\regenerator-runtime\runtime.js:62:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (%AppData%\Roaming\Sublime Text 3\Packages\HTML-CSS-JS Prettify\build\js-transpiled\node_modules\regenerator-runtime\runtime.js:288:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (%AppData%\Roaming\Sublime Text 3\Packages\HTML-CSS-JS Prettify\build\js-transpiled\node_modules\regenerator-runtime\runtime.js:114:21)
    at asyncGeneratorStep (%AppData%\Roaming\Sublime Text 3\Packages\HTML-CSS-JS Prettify\build\js-transpiled\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (%AppData%\Roaming\Sublime Text 3\Packages\HTML-CSS-JS Prettify\build\js-transpiled\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
```

**Comment by igor-ws** [comment]
I upgraded node.js to v8.12.0-x64 (Win installer) and now it works. Thanks @victorporof

**Comment by nganmcb** [comment]
ok, for my case, I rollback the latest Node to v8.12.0 and it works now

**Comment by victorporof** [comment]
Should still fix it for folks who cannot update node.

**Comment by StevenDStanton** [comment]
I am back up and running with Node 8.12

**Comment by victorporof** [comment]
Alright, so officially we need to support node > 6.14.4 
https://node.green/#ES2017-features-Object-static-methods-Object-entries

**Comment by peterchou2018** [comment]
Wow, I use Win 7 x64, and install the .msi file from officail website https://nodejs.org/en/download/
Then I don't need to restart my Windows, just launch the Sublime Text 3, it is ok now.

**Comment by victorporof** [comment]
Fixed in latest release https://github.com/victorporof/Sublime-HTMLPrettify/releases
