### ISSUE TITLE
Cannot find module 'core-js/modules/es7.object.entries'

### ISSUE THREAD

**Issue by zzt125306** [victorporof/Sublime-HTMLPrettify#617]
Cannot find module 'core-js/modules/es7.object.entries'

**Comment by diegocanal** [comment]
Have you tried the solution provided by @shlllshlll in [Issue \#613](https://github.com/victorporof/Sublime-HTMLPrettify/issues/613)?:

> A temporary solution:Go to the sublime packages folder, then go to HTML-CSS-JS Prettify. Finaly run npm install core-js in the current folder.

It worked for me.

**Comment by victorporof** [comment]
Sorry about the breakage!

Fixed now by https://github.com/victorporof/Sublime-HTMLPrettify/releases/tag/2.2.4

Should auto update soon :)
