### ISSUE TITLE
Prettifier gives error after updating Sublime

### ISSUE THREAD

**Issue by JanaVanMaele** [victorporof/Sublime-HTMLPrettify#618]
Updated Sublime Text to version 3.1.1 Build 3176.

'Prettify Code' command refuses to work and throws error.
I used the command for a string of html.
Tried again after restarting ST, but still the same error.

**Comment by diegocanal** [comment]
Have you tried the solution provided by @shlllshlll in [Issue \#613](https://github.com/victorporof/Sublime-HTMLPrettify/issues/613)?:

> A temporary solution:Go to the sublime packages folder, then go to HTML-CSS-JS Prettify. Finaly run npm install core-js in the current folder.

It worked for me.

**Comment by victorporof** [comment]
Sorry about the breakage!

Fixed now by https://github.com/victorporof/Sublime-HTMLPrettify/releases/tag/2.2.4

Should auto update soon :)
