### ISSUE TITLE
HTML Prettify broke again...

### ISSUE THREAD

**Issue by StevenDStanton** [victorporof/Sublime-HTMLPrettify#626]
Yesterday morning the addon stopped working and it started again when I upgraded my node.

This morning my node is at v8.12.0 abd the addon broke again

This time error

DPI mode: per-monitor v2
startup, version: 3176 windows x32 channel: stable
executable: /C/Program Files (x86)/Sublime Text 3/sublime_text.exe
working dir: /C/Program Files (x86)/Sublime Text 3
packages path: /C/Users/xxxx/AppData/Roaming/Sublime Text 3/Packages
state path: /C/Users/xxxx/AppData/Roaming/Sublime Text 3/Local
zip path: /C/Program Files (x86)/Sublime Text 3/Packages
zip path: /C/Users/xxxx/AppData/Roaming/Sublime Text 3/Installed Packages
ignored_packages: ["Vintage"]
pre session restore time: 0.379254
startup time: 0.586254
first paint time: 0.596254
reloading plugin Default.arithmetic
reloading plugin Default.auto_indent_tag
reloading plugin Default.block
reloading plugin Default.colors
reloading plugin Default.comment
reloading plugin Default.convert_color_scheme
reloading plugin Default.convert_syntax
reloading plugin Default.copy_path
reloading plugin Default.delete_word
reloading plugin Default.detect_indentation
reloading plugin Default.duplicate_line
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.indentation
reloading plugin Default.install_package_control
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_context_url
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.profile
reloading plugin Default.quick_panel
reloading plugin Default.rename
reloading plugin Default.run_syntax_tests
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.settings
reloading plugin Default.show_scope_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.swap_line
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.trim_trailing_white_space
reloading plugin Default.ui
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin ShellScript.ShellScript
reloading plugin 0_package_control_loader.00-package_control
reloading plugin 0_package_control_loader.55-jsonschema
reloading plugin AdvancedNewFile.AdvancedNewFile
reloading plugin DocBlockr.jsdocs
reloading plugin EditorConfig.EditorConfig
reloading plugin Nettuts+ Fetch.Fetch
reloading plugin Package Control.1_reloader
reloading plugin Package Control.2_bootstrap
reloading plugin Package Control.Package Control
reloading plugin React IDE.ReactIDE
reloading plugin SideBarEnhancements.SideBar
reloading plugin SideBarEnhancements.SideBarAPI
reloading plugin SideBarEnhancements.SideBarDefaultDisable
reloading plugin SublimeLinter-contrib-scss-lint.linter
scsslint: Defining 'cls.syntax' has been deprecated. Use http://www.sublimelinter.com/en/stable/linter_settings.html#selector
reloading plugin SublimeLinter.__init__
reloading plugin SublimeLinter.active_linters_view
reloading plugin SublimeLinter.busy_indicator_view
reloading plugin SublimeLinter.goto_commands
reloading plugin SublimeLinter.highlight_view
reloading plugin SublimeLinter.log_handler
reloading plugin SublimeLinter.message_view
reloading plugin SublimeLinter.panel_view
reloading plugin SublimeLinter.status_bar_view
reloading plugin SublimeLinter.sublime_linter
reloading plugin Trimmer.Trimmer
reloading plugin Babel.Babel
reloading plugin HTML-CSS-JS Prettify.HTMLPrettify
reloading plugin SFTP.SFTP
reloading plugin tern_for_sublime.tern
reloading plugin TypeScript.main
2018-10-02 09:56:44,140: 13604: WARNING: TypeScript plugin initialized.
plugins loaded
lang_service_enabled: True
Path of tsserver.js: C:\Users\xxxx\AppData\Roaming\Sublime Text 3\Packages\TypeScript\tsserver\tsserver.js
Path of tsc.js: C:\Users\xxxx\AppData\Roaming\Sublime Text 3\Packages\TypeScript\tsserver\tsc.js
Trying to spawn node executable from: node
ref view not found
reloading settings Packages/User/Fetch.sublime-settings
Package Control: Installing 2 upgrades
ignored packages updated to: ["HTML-CSS-JS Prettify", "SideBarEnhancements", "Vintage"]
reloading settings Packages/SideBarEnhancements/Side Bar.sublime-settings
unloading plugin SideBarEnhancements.SideBar
unloading plugin SideBarEnhancements.SideBarAPI
unloading plugin SideBarEnhancements.SideBarDefaultDisable
unloading plugin HTML-CSS-JS Prettify.HTMLPrettify
reloading settings Packages/HTML-CSS-JS Prettify/HTMLPrettify.sublime-settings
reloading settings Packages/User/Package Control.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
reloading settings Packages/User/Fetch.sublime-settings
Package Control: Upgraded HTML-CSS-JS Prettify to 2018.10.02.07.26.12
Package Control: Upgraded SideBarEnhancements to 5.0.23
ignored packages updated to: ["SideBarEnhancements", "Vintage"]
reloading plugin HTML-CSS-JS Prettify.HTMLPrettify
reloading settings Packages/HTML-CSS-JS Prettify/HTMLPrettify.sublime-settings
reloading settings Packages/User/Package Control.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
ignored packages updated to: ["Vintage"]
reloading settings Packages/SideBarEnhancements/Side Bar.sublime-settings
reloading plugin SideBarEnhancements.SideBar
reloading plugin SideBarEnhancements.SideBarAPI
reloading plugin SideBarEnhancements.SideBarDefaultDisable
reloading settings Packages/User/Package Control.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
reloading settings Packages/User/Fetch.sublime-settings
Node.js encountered a runtime error: module.js:550

    throw err;

    ^

Error: Cannot find module 'core-js/modules/es7.object.entries'

    at Function.Module._resolveFilename (module.js:548:15)

    at Function.Module._load (module.js:475:25)

    at Module.require (module.js:597:17)

    at require (internal/module.js:11:18)

    at Object.<anonymous> (C:\Users\xxxx\AppData\Roaming\Sublime Text 3\Packages\HTML-CSS-JS Prettify\build\js-transpiled\utils\configUtils.js:14:1)

    at Module._compile (module.js:653:30)

    at Object.Module._extensions..js (module.js:664:10)

    at Module.load (module.js:566:32)

    at tryModuleLoad (module.js:506:12)

    at Function.Module._load (module.js:498:3)

**Comment by codep0et** [comment]
@StevenDStanton Same error here, temporary fix is to go in the Package folder, so : C:\Users\xxxx\AppData\Roaming\Sublime Text 3\Packages\HTML-CSS-JS Prettify\ and run the command (from your command line) : npm i core-js --save

**Comment by victorporof** [comment]
Sorry about the breakage!

Fixed now by https://github.com/victorporof/Sublime-HTMLPrettify/releases/tag/2.2.4

Should auto update soon :)

**Comment by codep0et** [comment]
@victorporof Thank you :)
