### ISSUE TITLE
unexpected indent

### ISSUE THREAD

**Issue by Jentagawa** [victorporof/Sublime-HTMLPrettify#627]
after prettifying the following codes 
```html
<p><img src="" alt=""></p>
<p><img src="" alt=""></p>
```
the indent became like the following
```html
<p><img src="" alt=""></p>
       <p><img src="" alt=""></p>
```
after removing img tag from prettify preferences "List of tags that should not be reformatted" the indent resolved.
Its currently working fine but feels kinda weird removing img tag from "List of tags that should not be reformatted"

**Comment by victorporof** [comment]
Please file this issue at https://github.com/beautify-web/js-beautify
