### ISSUE TITLE
HTML-CSS-JS-PRETTIFY

### ISSUE THREAD

**Issue by wowoqu** [victorporof/Sublime-HTMLPrettify#630]
Node.js encountered a runtime error: internal/modules/cjs/loader.js:583

    throw err;

    ^
Error: Cannot find module 'core-js/modules/es7.object.entries'

**Comment by diegocanal** [comment]
Have you tried the solution provided by @shlllshlll?:

> A temporary solution:Go to the sublime packages folder, then go to HTML-CSS-JS Prettify. Finaly run npm install core-js in the current folder.

It worked for me.

**Comment by victorporof** [comment]
Sorry about the breakage!

Fixed now by https://github.com/victorporof/Sublime-HTMLPrettify/releases/tag/2.2.4

Should auto update soon :)
