### ISSUE TITLE
Can't use Prettify for Sublime Text 3 - Mac OS X

### ISSUE THREAD

**Issue by smartmediaman** [victorporof/Sublime-HTMLPrettify#634]
Please advise on fix or workaround for this asap.

Thank you.

**Comment by richie777cfc** [comment]
> Please advise on fix or workaround for this asap.
> 
> Thank you.

What is the issue you are facing?

**Comment by victorporof** [comment]
Couple of things you can try:

1. Update to latest node.
2. Update to latest version of this plugin: https://github.com/victorporof/Sublime-HTMLPrettify/releases/tag/2.2.5

**Comment by victorporof** [comment]
Also, please post the output in sublime's console.

**Comment by victorporof** [comment]
If not fixed by https://github.com/victorporof/Sublime-HTMLPrettify/releases/tag/2.2.5 please reopen this issue.
