### ISSUE TITLE
Pretify not working

### ISSUE THREAD

**Issue by shushmit-yadav** [victorporof/Sublime-HTMLPrettify#637]

**Comment by victorporof** [comment]
Couple of things you can try:

1. Update to latest node.
2. Update to latest version of this plugin: https://github.com/victorporof/Sublime-HTMLPrettify/releases/tag/2.2.5

What's the output in sublime's console?

**Comment by victorporof** [comment]
If not fixed by https://github.com/victorporof/Sublime-HTMLPrettify/releases/tag/2.2.5 please reopen this issue.
