### ISSUE TITLE
prettifier code  发生错误

### ISSUE THREAD

**Issue by hasapine** [victorporof/Sublime-HTMLPrettify#642]
A  runtime error was encountered in the prettifier. See the console output for more information.Do you wish to file a bug??

**Comment by victorporof** [comment]
What's the output in sublime's console?

**Comment by hasapine** [comment]
> What's the output in sublime's console?

[HTMLPrettify] Failed to parse file: C:\Users\pc\AppData\Roaming\Sublime Text 3\Packages\HTML-CSS-JS Prettify\.jsbeautifyrc.defaults.json
[HTMLPrettify] Attempting to parse file: C:\Users\pc\AppData\Roaming\Sublime Text 3\Packages\User\.jsbeautifyrc
[HTMLPrettify] Attempting to parse file: E:\workspace\homework-web\.editorconfig

**Comment by victorporof** [comment]
You've edited the jsbeautifyrc.defaults.json file and added a syntax error :)

How does your "prettify settings" file look like?

**Comment by hasapine** [comment]
> You've edited the jsbeautifyrc.defaults.json file and added a syntax error :)
> 
> How does your "prettify settings" file look like?

Thank you, I have solved this error, that error is wrong json format
