### ISSUE TITLE
div>img Indentation has errors.

### ISSUE THREAD

**Issue by jsoncode** [victorporof/Sublime-HTMLPrettify#643]
Indentation has errors.

![image](https://user-images.githubusercontent.com/13176273/46796502-70b12b80-cd7f-11e8-8fd5-1a454f5f8c4d.png)

**Comment by victorporof** [comment]
<img> is not a self closing html tag; this means that <img /> is invalid html as per spec.

But feel free to file this issue at 
https://github.com/beautify-web/js-beautify

**Comment by helloromero** [comment]
This issue is happening  with `<img>` it was fine before but now the indentation is wrong.
