### ISSUE TITLE
sibling node indented on <figure> tag

### ISSUE THREAD

**Issue by djdeo** [victorporof/Sublime-HTMLPrettify#644]
Expected

```html
<figure><img alt="alt" src="pic.png" /></figure>
<h2 id="summary">Summary</h2>
```
But got

``` html
<figure><img alt="alt" src="pic.png" /></figure>
    <h2 id="summary">Summary</h2>
```
Wrong indentation

**Comment by victorporof** [comment]
Please file this issue at https://github.com/beautify-web/js-beautify

But keep in mind that your html is malformed. `<img> is not a self-closing tag, as per the HTML5 spec.
