### ISSUE TITLE
Is there an HTML-CSS-JS Prettify plugin with vscode?

### ISSUE THREAD

**Issue by ayiaq1** [victorporof/Sublime-HTMLPrettify#645]
Does the author use vscode? If you have one, I hope to have a vscode version of the HTML-CSS-JS Prettify plugin. Because the formatting of vscode is too difficult!

**Comment by victorporof** [comment]
I do use vscode, but the marketplace is saturated with  formatters. So I thought I wouldn’t build yet another one.

**Comment by ayiaq1** [comment]
I have not found a HTML-CSS-JS unified formatted plugin. What format plugin do you use?
