### ISSUE TITLE
What is wrong with this snippet?

### ISSUE THREAD

**Issue by aszx0413** [victorporof/Sublime-HTMLPrettify#650]
![image](https://user-images.githubusercontent.com/2009321/47705313-22e26180-dc61-11e8-914d-9f84b4d6e543.png)
There is always a tab before `<div class="form-group">`
But when I wrap `img` With `span`, it works fine
![image](https://user-images.githubusercontent.com/2009321/47705390-5f15c200-dc61-11e8-8a00-08b324cddafd.png)

Can anyone tell me why? It drives me crazy in prettify

**Comment by victorporof** [comment]
This should be fixed in the latest version, try upgrading.

If not, please file this issue at https://github.com/beautify-web/js-beautify
