### ISSUE TITLE
Feature-Request: Vue: Add option to prepend 1 indent block on script tag

### ISSUE THREAD

**Issue by romanzipp** [victorporof/Sublime-HTMLPrettify#652]
I would like to have thw following two options on **Vue** files.

- ~add **one ident block** in the script tag~
- don't remove the first space after opening `<script>` tag

Currently, HTMLPrettify transforms ...

```html
<script>

    import { mapGetters, mapActions } from 'vuex';

    export default {

        computed: {
            ...mapGetters('meta', ['breadcrumbs']),
        },
    }

</script>
```

... to ...

```html
<script>
import { mapGetters, mapActions } from 'vuex';

export default {

    computed: {
        ...mapGetters('meta', ['breadcrumbs']),
    },
}
</script>

```

**Comment by romanzipp** [comment]
Just found out that the `"indent_scripts": "normal"` option in the html namespace solves my first issue with script tag indenting.

**Comment by victorporof** [comment]
Please file this issue at https://github.com/beautify-web/js-beautify
