### ISSUE TITLE
indent error

### ISSUE THREAD

**Issue by guohuihot** [victorporof/Sublime-HTMLPrettify#656]
expected
![image](https://user-images.githubusercontent.com/3119995/49640726-4317f400-fa49-11e8-944e-663ce3e8e296.png)
but got
![image](https://user-images.githubusercontent.com/3119995/49640752-50cd7980-fa49-11e8-8c09-59586c065133.png)

**Comment by victorporof** [comment]
Please file this issue at https://github.com/beautify-web/js-beautify
