### ISSUE TITLE
A runtime error was encountered in the prettifier.

### ISSUE THREAD

**Issue by jkevintu** [victorporof/Sublime-HTMLPrettify#661]
Reinstall the package, and the error still occur.
Version:
<img width="581" alt="screen shot 2019-01-03 at 11 38 29 am" src="https://user-images.githubusercontent.com/480763/50649522-1c67b300-0f4c-11e9-9437-f95b788440a3.png">
Sublime 3.1.1
MacOS 10.13.6

Error in console:
```
Node.js encountered a runtime error: dyld: Library not loaded: /usr/local/opt/icu4c/lib/libicui18n.59.dylib
  Referenced from: /usr/local/bin/node
  Reason: image not found
```

**Comment by victorporof** [comment]
What's your node version?

**Comment by majman** [comment]
@victorporof 
Same problem...
`node -v: v8.11.3`

**Comment by jkevintu** [comment]
@victorporof @majman This runtime issue has been fixed for me.
Node `v9.3.0`
Sublime `3.2`
