### ISSUE TITLE
Anyway to add csutom spaces/lines in HTML? 

### ISSUE THREAD

**Issue by Abd-Ur-Rehman** [victorporof/Sublime-HTMLPrettify#665]
I'm trying to figure out how to add some custom space/line after some divs but can't find any info. 

For example: 

> <body>
    <nav class="navigation">
        <ul class="navigation-menu">
            <li class="menu-item"><a href="#">Home</a></li>
            <li class="menu-item"><a href="#">About</a></li>
            <li class="menu-item"><a href="#">Blog</a></li>
            <li class="menu-item"><a href="#">Support</a></li>
            <li class="menu-item"><a href="#">Contact</a></li>
        </ul>
    </nav>
</body>

After that nav, here I want to add some lines then a new div but on save it just moves up my elements. Can I add some custom space or lines with the **"format_on_save": true,**

If there are settings for this then could you point me out to them?

**Comment by Abd-Ur-Rehman** [comment]
@victorporof Is there any workaround for this?

**Comment by victorporof** [comment]
You should file this issue at https://github.com/beautify-web/js-beautify
