### ISSUE TITLE
Error trying to parse settings

### ISSUE THREAD

**Issue by James-Silva3** [victorporof/Sublime-HTMLPrettify#673]
Error trying to parse settings:Expected value in Packages\HTML-CSS-JS Prettify\HTMLPrettify.sublime-settings:1:1

**Comment by victorporof** [comment]
Did you delete `HTMLPrettify.sublime-settings`? What is the contents of that file?

**Comment by James-Silva3** [comment]
Its now ok, I delete the HTMLPrettify in my pc and install again the HTML-CSS Preffity. thank you
