### ISSUE TITLE
Sublime Text 3: Unindents when Ctrl + Save

### ISSUE THREAD

**Issue by Sophiecli** [victorporof/Sublime-HTMLPrettify#677]
Hello there, 
I am unsure why Sublime Text ignores all of my packages and user settings for every file format (html, css, ruby, rails, etc) - I have put in reindent_on_save: true and followed almost every instruction and suggestion on StackOverflow and GitHub and not able to save the code with the indents! 

Please advise what exactly I need to have in my settings please.

**Comment by victorporof** [comment]
What comes to mind is that you may have another plugin that overrides this prettifier's output on save. Anything other plugin that you have and may do this that comes to mind?

**Comment by Sophiecli** [comment]
Hello @victorporof - thank you! You had given me a suggestion that I have not thought before. I went into Package Control and disabled all the packages that was related to indenting and then re-installed one. I think that was the culprit. 

Thanks!

**Comment by victorporof** [comment]
Glad you found the culprit.
