### ISSUE TITLE
Cannot prettify code in .ejs file (not .html)

### ISSUE THREAD

**Issue by beanbocchi** [victorporof/Sublime-HTMLPrettify#703]
Every time I prettify the .ejs file first I must rename it into .html, so I can prettify it, then rename it into .ejs
This taking my time too much :(

**Comment by machinewu** [comment]
Click `Preferences -> Package Settings -> HTML/CSS/JS Prettify -> Plugins Options - User`

You can set it like follow:
```
{
    "global_file_rules":
    {
        "js":
            {
                "allowed_file_extensions": ["js", "jsx", "ejs"],
                "allowed_file_syntaxes": ["javascript", "ecma", "react", "babel"],
                "disallowed_file_patterns": []
            }
     }
}
```

Or if your ejs is like html, set "ejs" to "global_file_rules -> html" config
You can refer to (Of course, you can copy) the default configuration at `Preferences -> Package Settings -> HTML/CSS/JS Prettify -> Plugins Options - Default`
