### ISSUE TITLE
Can I use sublime user setting override the default

### ISSUE THREAD

**Issue by popomore** [victorporof/Sublime-HTMLPrettify#79]
So I can sync the config between different computer.

**Comment by felixhao28** [comment]
+1 on this. This is a quite fundamental function for any serious plugin.

**Comment by victorporof** [comment]
See the readme: https://github.com/victorporof/Sublime-HTMLPrettify#using-your-own-jsbeautifyrc-options 

You can put that file anywhere you want if it's in the project's directory chain, or in the home folder. Having dotfiles in your home is a very common practice.
